/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of possible entity types within the system.
 * @export
 */
export const ApplicationEntityType = {
    Workspace: 'WORKSPACE',
    BlockType: 'BLOCK_TYPE',
    Block: 'BLOCK',
    User: 'USER',
    Entity: 'ENTITY',
    EntityType: 'ENTITY_TYPE',
    WorkflowDefinition: 'WORKFLOW_DEFINITION',
    WorkflowNode: 'WORKFLOW_NODE',
    WorkflowEdge: 'WORKFLOW_EDGE'
} as const;
export type ApplicationEntityType = typeof ApplicationEntityType[keyof typeof ApplicationEntityType];


export function instanceOfApplicationEntityType(value: any): boolean {
    for (const key in ApplicationEntityType) {
        if (Object.prototype.hasOwnProperty.call(ApplicationEntityType, key)) {
            if (ApplicationEntityType[key as keyof typeof ApplicationEntityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApplicationEntityTypeFromJSON(json: any): ApplicationEntityType {
    return ApplicationEntityTypeFromJSONTyped(json, false);
}

export function ApplicationEntityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationEntityType {
    return json as ApplicationEntityType;
}

export function ApplicationEntityTypeToJSON(value?: ApplicationEntityType | null): any {
    return value as any;
}

export function ApplicationEntityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApplicationEntityType {
    return value as ApplicationEntityType;
}

