/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockTree } from './BlockTree';
import {
    BlockTreeFromJSON,
    BlockTreeFromJSONTyped,
    BlockTreeToJSON,
    BlockTreeToJSONTyped,
} from './BlockTree';
import type { BlockTreeLayout } from './BlockTreeLayout';
import {
    BlockTreeLayoutFromJSON,
    BlockTreeLayoutFromJSONTyped,
    BlockTreeLayoutToJSON,
    BlockTreeLayoutToJSONTyped,
} from './BlockTreeLayout';

/**
 * 
 * @export
 * @interface BlockEnvironment
 */
export interface BlockEnvironment {
    /**
     * 
     * @type {BlockTreeLayout}
     * @memberof BlockEnvironment
     */
    layout: BlockTreeLayout;
    /**
     * 
     * @type {Array<BlockTree>}
     * @memberof BlockEnvironment
     */
    trees: Array<BlockTree>;
}

/**
 * Check if a given object implements the BlockEnvironment interface.
 */
export function instanceOfBlockEnvironment(value: object): value is BlockEnvironment {
    if (!('layout' in value) || value['layout'] === undefined) return false;
    if (!('trees' in value) || value['trees'] === undefined) return false;
    return true;
}

export function BlockEnvironmentFromJSON(json: any): BlockEnvironment {
    return BlockEnvironmentFromJSONTyped(json, false);
}

export function BlockEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockEnvironment {
    if (json == null) {
        return json;
    }
    return {
        
        'layout': BlockTreeLayoutFromJSON(json['layout']),
        'trees': ((json['trees'] as Array<any>).map(BlockTreeFromJSON)),
    };
}

export function BlockEnvironmentToJSON(json: any): BlockEnvironment {
    return BlockEnvironmentToJSONTyped(json, false);
}

export function BlockEnvironmentToJSONTyped(value?: BlockEnvironment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layout': BlockTreeLayoutToJSON(value['layout']),
        'trees': ((value['trees'] as Array<any>).map(BlockTreeToJSON)),
    };
}

