/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockType } from './BlockType';
import {
  BlockTypeFromJSON,
  BlockTypeFromJSONTyped,
  BlockTypeToJSON,
  BlockTypeToJSONTyped,
} from './BlockType';
import type { BlockPayload } from './BlockPayload';
import {
  BlockPayloadFromJSON,
  BlockPayloadFromJSONTyped,
  BlockPayloadToJSON,
  BlockPayloadToJSONTyped,
} from './BlockPayload';

/**
 *
 * @export
 * @interface Block
 */
export interface Block {
  /**
   *
   * @type {string}
   * @memberof Block
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Block
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Block
   */
  workspaceId: string;
  /**
   *
   * @type {BlockType}
   * @memberof Block
   */
  type: BlockType;
  /**
   *
   * @type {BlockPayload}
   * @memberof Block
   */
  payload: BlockPayload;
  /**
   *
   * @type {Array<string>}
   * @memberof Block
   */
  validationErrors?: Array<string>;
  /**
   *
   * @type {Date}
   * @memberof Block
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof Block
   */
  updatedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof Block
   */
  createdBy?: string;
  /**
   *
   * @type {string}
   * @memberof Block
   */
  updatedBy?: string;
}

/**
 * Check if a given object implements the Block interface.
 */
export function instanceOfBlock(value: object): value is Block {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('payload' in value) || value['payload'] === undefined) return false;
  return true;
}

export function BlockFromJSON(json: any): Block {
  return BlockFromJSONTyped(json, false);
}

export function BlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): Block {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'] == null ? undefined : json['name'],
    workspaceId: json['workspaceId'],
    type: BlockTypeFromJSON(json['type']),
    payload: BlockPayloadFromJSON(json['payload']),
    validationErrors: json['validationErrors'] == null ? undefined : json['validationErrors'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    createdBy: json['createdBy'] == null ? undefined : json['createdBy'],
    updatedBy: json['updatedBy'] == null ? undefined : json['updatedBy'],
  };
}

export function BlockToJSON(json: any): Block {
  return BlockToJSONTyped(json, false);
}

export function BlockToJSONTyped(value?: Block | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    workspaceId: value['workspaceId'],
    type: BlockTypeToJSON(value['type']),
    payload: BlockPayloadToJSON(value['payload']),
    validationErrors: value['validationErrors'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    createdBy: value['createdBy'],
    updatedBy: value['updatedBy'],
  };
}
