/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BlockMetadataType = {
  Content: 'CONTENT',
  EntityReference: 'ENTITY_REFERENCE',
  BlockReference: 'BLOCK_REFERENCE',
} as const;
export type BlockMetadataType = (typeof BlockMetadataType)[keyof typeof BlockMetadataType];

export function instanceOfBlockMetadataType(value: any): boolean {
  for (const key in BlockMetadataType) {
    if (Object.prototype.hasOwnProperty.call(BlockMetadataType, key)) {
      if (BlockMetadataType[key as keyof typeof BlockMetadataType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function BlockMetadataTypeFromJSON(json: any): BlockMetadataType {
  return BlockMetadataTypeFromJSONTyped(json, false);
}

export function BlockMetadataTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BlockMetadataType {
  return json as BlockMetadataType;
}

export function BlockMetadataTypeToJSON(value?: BlockMetadataType | null): any {
  return value as any;
}

export function BlockMetadataTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): BlockMetadataType {
  return value as BlockMetadataType;
}
