/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BlockListOrderingMode {
    Manual = 'MANUAL',
    Sorted = 'SORTED'
}


export function instanceOfBlockListOrderingMode(value: any): boolean {
    for (const key in BlockListOrderingMode) {
        if (Object.prototype.hasOwnProperty.call(BlockListOrderingMode, key)) {
            if (BlockListOrderingMode[key as keyof typeof BlockListOrderingMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlockListOrderingModeFromJSON(json: any): BlockListOrderingMode {
    return BlockListOrderingModeFromJSONTyped(json, false);
}

export function BlockListOrderingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockListOrderingMode {
    return json as BlockListOrderingMode;
}

export function BlockListOrderingModeToJSON(value?: BlockListOrderingMode | null): any {
    return value as any;
}

export function BlockListOrderingModeToJSONTyped(value: any, ignoreDiscriminator: boolean): BlockListOrderingMode {
    return value as BlockListOrderingMode;
}

