/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockListConfiguration } from './BlockListConfiguration';
import {
    BlockListConfigurationFromJSON,
    BlockListConfigurationFromJSONTyped,
    BlockListConfigurationToJSON,
    BlockListConfigurationToJSONTyped,
} from './BlockListConfiguration';
import type { BlockMetadataType } from './BlockMetadataType';
import {
    BlockMetadataTypeFromJSON,
    BlockMetadataTypeFromJSONTyped,
    BlockMetadataTypeToJSON,
    BlockMetadataTypeToJSONTyped,
} from './BlockMetadataType';
import type { BlockMeta } from './BlockMeta';
import {
    BlockMetaFromJSON,
    BlockMetaFromJSONTyped,
    BlockMetaToJSON,
    BlockMetaToJSONTyped,
} from './BlockMeta';

/**
 * 
 * @export
 * @interface BlockContentMetadata
 */
export interface BlockContentMetadata {
    /**
     * 
     * @type {BlockMeta}
     * @memberof BlockContentMetadata
     */
    meta: BlockMeta;
    /**
     * 
     * @type {boolean}
     * @memberof BlockContentMetadata
     */
    readonly: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockContentMetadata
     */
    deletable: boolean;
    /**
     * 
     * @type {BlockMetadataType}
     * @memberof BlockContentMetadata
     */
    type: BlockMetadataType;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BlockContentMetadata
     */
    data: { [key: string]: any; };
    /**
     * 
     * @type {BlockListConfiguration}
     * @memberof BlockContentMetadata
     */
    listConfig?: BlockListConfiguration;
}



/**
 * Check if a given object implements the BlockContentMetadata interface.
 */
export function instanceOfBlockContentMetadata(value: object): value is BlockContentMetadata {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('readonly' in value) || value['readonly'] === undefined) return false;
    if (!('deletable' in value) || value['deletable'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BlockContentMetadataFromJSON(json: any): BlockContentMetadata {
    return BlockContentMetadataFromJSONTyped(json, false);
}

export function BlockContentMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockContentMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': BlockMetaFromJSON(json['meta']),
        'readonly': json['readonly'],
        'deletable': json['deletable'],
        'type': BlockMetadataTypeFromJSON(json['type']),
        'data': json['data'],
        'listConfig': json['listConfig'] == null ? undefined : BlockListConfigurationFromJSON(json['listConfig']),
    };
}

export function BlockContentMetadataToJSON(json: any): BlockContentMetadata {
    return BlockContentMetadataToJSONTyped(json, false);
}

export function BlockContentMetadataToJSONTyped(value?: BlockContentMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': BlockMetaToJSON(value['meta']),
        'readonly': value['readonly'],
        'deletable': value['deletable'],
        'type': BlockMetadataTypeToJSON(value['type']),
        'data': value['data'],
        'listConfig': BlockListConfigurationToJSON(value['listConfig']),
    };
}

