/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DeleteAction {
    RemoveBidirectional = 'REMOVE_BIDIRECTIONAL',
    RemoveEntityType = 'REMOVE_ENTITY_TYPE',
    DeleteRelationship = 'DELETE_RELATIONSHIP'
}


export function instanceOfDeleteAction(value: any): boolean {
    for (const key in DeleteAction) {
        if (Object.prototype.hasOwnProperty.call(DeleteAction, key)) {
            if (DeleteAction[key as keyof typeof DeleteAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeleteActionFromJSON(json: any): DeleteAction {
    return DeleteActionFromJSONTyped(json, false);
}

export function DeleteActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAction {
    return json as DeleteAction;
}

export function DeleteActionToJSON(value?: DeleteAction | null): any {
    return value as any;
}

export function DeleteActionToJSONTyped(value: any, ignoreDiscriminator: boolean): DeleteAction {
    return value as DeleteAction;
}

