/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityTypeRequestDefinition } from './EntityTypeRequestDefinition';
import {
  EntityTypeRequestDefinitionFromJSON,
  EntityTypeRequestDefinitionFromJSONTyped,
  EntityTypeRequestDefinitionToJSON,
  EntityTypeRequestDefinitionToJSONTyped,
} from './EntityTypeRequestDefinition';

/**
 * Request to remove a schema attribute definition for an entity type
 * @export
 * @interface DeleteAttributeDefinitionRequest
 */
export interface DeleteAttributeDefinitionRequest {
  /**
   *
   * @type {string}
   * @memberof DeleteAttributeDefinitionRequest
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof DeleteAttributeDefinitionRequest
   */
  id: string;
  /**
   *
   * @type {EntityTypeRequestDefinition}
   * @memberof DeleteAttributeDefinitionRequest
   */
  type: EntityTypeRequestDefinition;
}

/**
 * Check if a given object implements the DeleteAttributeDefinitionRequest interface.
 */
export function instanceOfDeleteAttributeDefinitionRequest(
  value: object,
): value is DeleteAttributeDefinitionRequest {
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  return true;
}

export function DeleteAttributeDefinitionRequestFromJSON(
  json: any,
): DeleteAttributeDefinitionRequest {
  return DeleteAttributeDefinitionRequestFromJSONTyped(json, false);
}

export function DeleteAttributeDefinitionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteAttributeDefinitionRequest {
  if (json == null) {
    return json;
  }
  return {
    key: json['key'],
    id: json['id'],
    type: EntityTypeRequestDefinitionFromJSON(json['type']),
  };
}

export function DeleteAttributeDefinitionRequestToJSON(
  json: any,
): DeleteAttributeDefinitionRequest {
  return DeleteAttributeDefinitionRequestToJSONTyped(json, false);
}

export function DeleteAttributeDefinitionRequestToJSONTyped(
  value?: DeleteAttributeDefinitionRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value['key'],
    id: value['id'],
    type: EntityTypeRequestDefinitionToJSON(value['type']),
  };
}
