/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EntityTypeRequestDefinition {
    SaveRelationship = 'SAVE_RELATIONSHIP',
    SaveSchema = 'SAVE_SCHEMA',
    DeleteSchema = 'DELETE_SCHEMA',
    DeleteRelationship = 'DELETE_RELATIONSHIP'
}


export function instanceOfEntityTypeRequestDefinition(value: any): boolean {
    for (const key in EntityTypeRequestDefinition) {
        if (Object.prototype.hasOwnProperty.call(EntityTypeRequestDefinition, key)) {
            if (EntityTypeRequestDefinition[key as keyof typeof EntityTypeRequestDefinition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntityTypeRequestDefinitionFromJSON(json: any): EntityTypeRequestDefinition {
    return EntityTypeRequestDefinitionFromJSONTyped(json, false);
}

export function EntityTypeRequestDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityTypeRequestDefinition {
    return json as EntityTypeRequestDefinition;
}

export function EntityTypeRequestDefinitionToJSON(value?: EntityTypeRequestDefinition | null): any {
    return value as any;
}

export function EntityTypeRequestDefinitionToJSONTyped(value: any, ignoreDiscriminator: boolean): EntityTypeRequestDefinition {
    return value as EntityTypeRequestDefinition;
}

