/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityPropertyType } from './EntityPropertyType';
import {
  EntityPropertyTypeFromJSON,
  EntityPropertyTypeFromJSONTyped,
  EntityPropertyTypeToJSON,
  EntityPropertyTypeToJSONTyped,
} from './EntityPropertyType';

/**
 *
 * @export
 * @interface EntityTypeAttributeColumn
 */
export interface EntityTypeAttributeColumn {
  /**
   *
   * @type {string}
   * @memberof EntityTypeAttributeColumn
   */
  key: string;
  /**
   *
   * @type {EntityPropertyType}
   * @memberof EntityTypeAttributeColumn
   */
  type: EntityPropertyType;
  /**
   *
   * @type {number}
   * @memberof EntityTypeAttributeColumn
   */
  width: number;
}

/**
 * Check if a given object implements the EntityTypeAttributeColumn interface.
 */
export function instanceOfEntityTypeAttributeColumn(
  value: object,
): value is EntityTypeAttributeColumn {
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('width' in value) || value['width'] === undefined) return false;
  return true;
}

export function EntityTypeAttributeColumnFromJSON(json: any): EntityTypeAttributeColumn {
  return EntityTypeAttributeColumnFromJSONTyped(json, false);
}

export function EntityTypeAttributeColumnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntityTypeAttributeColumn {
  if (json == null) {
    return json;
  }
  return {
    key: json['key'],
    type: EntityPropertyTypeFromJSON(json['type']),
    width: json['width'],
  };
}

export function EntityTypeAttributeColumnToJSON(json: any): EntityTypeAttributeColumn {
  return EntityTypeAttributeColumnToJSONTyped(json, false);
}

export function EntityTypeAttributeColumnToJSONTyped(
  value?: EntityTypeAttributeColumn | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value['key'],
    type: EntityPropertyTypeToJSON(value['type']),
    width: value['width'],
  };
}
