/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EntityTypeRelationshipDataLossReason {
    RelationshipDeleted = 'RELATIONSHIP_DELETED',
    EntityTypeRemovedFromTarget = 'ENTITY_TYPE_REMOVED_FROM_TARGET',
    CardinalityRestriction = 'CARDINALITY_RESTRICTION'
}


export function instanceOfEntityTypeRelationshipDataLossReason(value: any): boolean {
    for (const key in EntityTypeRelationshipDataLossReason) {
        if (Object.prototype.hasOwnProperty.call(EntityTypeRelationshipDataLossReason, key)) {
            if (EntityTypeRelationshipDataLossReason[key as keyof typeof EntityTypeRelationshipDataLossReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntityTypeRelationshipDataLossReasonFromJSON(json: any): EntityTypeRelationshipDataLossReason {
    return EntityTypeRelationshipDataLossReasonFromJSONTyped(json, false);
}

export function EntityTypeRelationshipDataLossReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityTypeRelationshipDataLossReason {
    return json as EntityTypeRelationshipDataLossReason;
}

export function EntityTypeRelationshipDataLossReasonToJSON(value?: EntityTypeRelationshipDataLossReason | null): any {
    return value as any;
}

export function EntityTypeRelationshipDataLossReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): EntityTypeRelationshipDataLossReason {
    return value as EntityTypeRelationshipDataLossReason;
}

