/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityType } from './EntityType';
import {
  EntityTypeFromJSON,
  EntityTypeFromJSONTyped,
  EntityTypeToJSON,
  EntityTypeToJSONTyped,
} from './EntityType';
import type { EntityTypeRelationshipImpactAnalysis } from './EntityTypeRelationshipImpactAnalysis';
import {
  EntityTypeRelationshipImpactAnalysisFromJSON,
  EntityTypeRelationshipImpactAnalysisFromJSONTyped,
  EntityTypeRelationshipImpactAnalysisToJSON,
  EntityTypeRelationshipImpactAnalysisToJSONTyped,
} from './EntityTypeRelationshipImpactAnalysis';

/**
 *
 * @export
 * @interface EntityTypeImpactResponse
 */
export interface EntityTypeImpactResponse {
  /**
   *
   * @type {string}
   * @memberof EntityTypeImpactResponse
   */
  error?: string;
  /**
   *
   * @type {{ [key: string]: EntityType; }}
   * @memberof EntityTypeImpactResponse
   */
  updatedEntityTypes?: { [key: string]: EntityType };
  /**
   *
   * @type {EntityTypeRelationshipImpactAnalysis}
   * @memberof EntityTypeImpactResponse
   */
  impact?: EntityTypeRelationshipImpactAnalysis;
}

/**
 * Check if a given object implements the EntityTypeImpactResponse interface.
 */
export function instanceOfEntityTypeImpactResponse(
  value: object,
): value is EntityTypeImpactResponse {
  return true;
}

export function EntityTypeImpactResponseFromJSON(json: any): EntityTypeImpactResponse {
  return EntityTypeImpactResponseFromJSONTyped(json, false);
}

export function EntityTypeImpactResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntityTypeImpactResponse {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
    updatedEntityTypes:
      json['updatedEntityTypes'] == null
        ? undefined
        : mapValues(json['updatedEntityTypes'], EntityTypeFromJSON),
    impact:
      json['impact'] == null
        ? undefined
        : EntityTypeRelationshipImpactAnalysisFromJSON(json['impact']),
  };
}

export function EntityTypeImpactResponseToJSON(json: any): EntityTypeImpactResponse {
  return EntityTypeImpactResponseToJSONTyped(json, false);
}

export function EntityTypeImpactResponseToJSONTyped(
  value?: EntityTypeImpactResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
    updatedEntityTypes:
      value['updatedEntityTypes'] == null
        ? undefined
        : mapValues(value['updatedEntityTypes'], EntityTypeToJSON),
    impact: EntityTypeRelationshipImpactAnalysisToJSON(value['impact']),
  };
}
