/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecutionQueueStatus } from './ExecutionQueueStatus';
import {
  ExecutionQueueStatusFromJSON,
  ExecutionQueueStatusFromJSONTyped,
  ExecutionQueueStatusToJSON,
  ExecutionQueueStatusToJSONTyped,
} from './ExecutionQueueStatus';

/**
 *
 * @export
 * @interface ExecutionQueueRequest
 */
export interface ExecutionQueueRequest {
  /**
   *
   * @type {string}
   * @memberof ExecutionQueueRequest
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ExecutionQueueRequest
   */
  workspaceId: string;
  /**
   *
   * @type {string}
   * @memberof ExecutionQueueRequest
   */
  workflowDefinitionId: string;
  /**
   *
   * @type {string}
   * @memberof ExecutionQueueRequest
   */
  executionId?: string;
  /**
   *
   * @type {ExecutionQueueStatus}
   * @memberof ExecutionQueueRequest
   */
  status: ExecutionQueueStatus;
  /**
   *
   * @type {Date}
   * @memberof ExecutionQueueRequest
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ExecutionQueueRequest
   */
  claimedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ExecutionQueueRequest
   */
  dispatchedAt?: Date;
  /**
   *
   * @type {number}
   * @memberof ExecutionQueueRequest
   */
  attemptCount: number;
  /**
   *
   * @type {string}
   * @memberof ExecutionQueueRequest
   */
  lastError?: string;
}

/**
 * Check if a given object implements the ExecutionQueueRequest interface.
 */
export function instanceOfExecutionQueueRequest(value: object): value is ExecutionQueueRequest {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
  if (!('workflowDefinitionId' in value) || value['workflowDefinitionId'] === undefined)
    return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('attemptCount' in value) || value['attemptCount'] === undefined) return false;
  return true;
}

export function ExecutionQueueRequestFromJSON(json: any): ExecutionQueueRequest {
  return ExecutionQueueRequestFromJSONTyped(json, false);
}

export function ExecutionQueueRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExecutionQueueRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    workspaceId: json['workspaceId'],
    workflowDefinitionId: json['workflowDefinitionId'],
    executionId: json['executionId'] == null ? undefined : json['executionId'],
    status: ExecutionQueueStatusFromJSON(json['status']),
    createdAt: new Date(json['createdAt']),
    claimedAt: json['claimedAt'] == null ? undefined : new Date(json['claimedAt']),
    dispatchedAt: json['dispatchedAt'] == null ? undefined : new Date(json['dispatchedAt']),
    attemptCount: json['attemptCount'],
    lastError: json['lastError'] == null ? undefined : json['lastError'],
  };
}

export function ExecutionQueueRequestToJSON(json: any): ExecutionQueueRequest {
  return ExecutionQueueRequestToJSONTyped(json, false);
}

export function ExecutionQueueRequestToJSONTyped(
  value?: ExecutionQueueRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    workspaceId: value['workspaceId'],
    workflowDefinitionId: value['workflowDefinitionId'],
    executionId: value['executionId'],
    status: ExecutionQueueStatusToJSON(value['status']),
    createdAt: value['createdAt'].toISOString(),
    claimedAt: value['claimedAt'] == null ? value['claimedAt'] : value['claimedAt'].toISOString(),
    dispatchedAt:
      value['dispatchedAt'] == null ? value['dispatchedAt'] : value['dispatchedAt'].toISOString(),
    attemptCount: value['attemptCount'],
    lastError: value['lastError'],
  };
}
