/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GridRect } from './GridRect';
import {
  GridRectFromJSON,
  GridRectFromJSONTyped,
  GridRectToJSON,
  GridRectToJSONTyped,
} from './GridRect';
import type { LayoutGridItem } from './LayoutGridItem';
import {
  LayoutGridItemFromJSON,
  LayoutGridItemFromJSONTyped,
  LayoutGridItemToJSON,
  LayoutGridItemToJSONTyped,
} from './LayoutGridItem';

/**
 *
 * @export
 * @interface LayoutGrid
 */
export interface LayoutGrid {
  /**
   *
   * @type {GridRect}
   * @memberof LayoutGrid
   */
  layout: GridRect;
  /**
   *
   * @type {Array<LayoutGridItem>}
   * @memberof LayoutGrid
   */
  items: Array<LayoutGridItem>;
}

/**
 * Check if a given object implements the LayoutGrid interface.
 */
export function instanceOfLayoutGrid(value: object): value is LayoutGrid {
  if (!('layout' in value) || value['layout'] === undefined) return false;
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function LayoutGridFromJSON(json: any): LayoutGrid {
  return LayoutGridFromJSONTyped(json, false);
}

export function LayoutGridFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutGrid {
  if (json == null) {
    return json;
  }
  return {
    layout: GridRectFromJSON(json['layout']),
    items: (json['items'] as Array<any>).map(LayoutGridItemFromJSON),
  };
}

export function LayoutGridToJSON(json: any): LayoutGrid {
  return LayoutGridToJSONTyped(json, false);
}

export function LayoutGridToJSONTyped(
  value?: LayoutGrid | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    layout: GridRectToJSON(value['layout']),
    items: (value['items'] as Array<any>).map(LayoutGridItemToJSON),
  };
}
