/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ListFilterLogicType = {
    And: 'AND',
    Or: 'OR'
} as const;
export type ListFilterLogicType = typeof ListFilterLogicType[keyof typeof ListFilterLogicType];


export function instanceOfListFilterLogicType(value: any): boolean {
    for (const key in ListFilterLogicType) {
        if (Object.prototype.hasOwnProperty.call(ListFilterLogicType, key)) {
            if (ListFilterLogicType[key as keyof typeof ListFilterLogicType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ListFilterLogicTypeFromJSON(json: any): ListFilterLogicType {
    return ListFilterLogicTypeFromJSONTyped(json, false);
}

export function ListFilterLogicTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFilterLogicType {
    return json as ListFilterLogicType;
}

export function ListFilterLogicTypeToJSON(value?: ListFilterLogicType | null): any {
    return value as any;
}

export function ListFilterLogicTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ListFilterLogicType {
    return value as ListFilterLogicType;
}

