/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockListOrderingMode } from './BlockListOrderingMode';
import {
    BlockListOrderingModeFromJSON,
    BlockListOrderingModeFromJSONTyped,
    BlockListOrderingModeToJSON,
    BlockListOrderingModeToJSONTyped,
} from './BlockListOrderingMode';
import type { ListFilterLogicType } from './ListFilterLogicType';
import {
    ListFilterLogicTypeFromJSON,
    ListFilterLogicTypeFromJSONTyped,
    ListFilterLogicTypeToJSON,
    ListFilterLogicTypeToJSONTyped,
} from './ListFilterLogicType';
import type { FilterSpec } from './FilterSpec';
import {
    FilterSpecFromJSON,
    FilterSpecFromJSONTyped,
    FilterSpecToJSON,
    FilterSpecToJSONTyped,
} from './FilterSpec';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface ListConfig
 */
export interface ListConfig {
    /**
     * 
     * @type {BlockListOrderingMode}
     * @memberof ListConfig
     */
    mode: BlockListOrderingMode;
    /**
     * 
     * @type {SortSpec}
     * @memberof ListConfig
     */
    sort?: SortSpec;
    /**
     * 
     * @type {Array<FilterSpec>}
     * @memberof ListConfig
     */
    filters: Array<FilterSpec>;
    /**
     * 
     * @type {ListFilterLogicType}
     * @memberof ListConfig
     */
    filterLogic: ListFilterLogicType;
}



/**
 * Check if a given object implements the ListConfig interface.
 */
export function instanceOfListConfig(value: object): value is ListConfig {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('filterLogic' in value) || value['filterLogic'] === undefined) return false;
    return true;
}

export function ListConfigFromJSON(json: any): ListConfig {
    return ListConfigFromJSONTyped(json, false);
}

export function ListConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': BlockListOrderingModeFromJSON(json['mode']),
        'sort': json['sort'] == null ? undefined : SortSpecFromJSON(json['sort']),
        'filters': ((json['filters'] as Array<any>).map(FilterSpecFromJSON)),
        'filterLogic': ListFilterLogicTypeFromJSON(json['filterLogic']),
    };
}

export function ListConfigToJSON(json: any): ListConfig {
    return ListConfigToJSONTyped(json, false);
}

export function ListConfigToJSONTyped(value?: ListConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': BlockListOrderingModeToJSON(value['mode']),
        'sort': SortSpecToJSON(value['sort']),
        'filters': ((value['filters'] as Array<any>).map(FilterSpecToJSON)),
        'filterLogic': ListFilterLogicTypeToJSON(value['filterLogic']),
    };
}

