/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockMetadataType } from './BlockMetadataType';
import {
  BlockMetadataTypeFromJSON,
  BlockMetadataTypeFromJSONTyped,
  BlockMetadataTypeToJSON,
  BlockMetadataTypeToJSONTyped,
} from './BlockMetadataType';
import type { BlockMeta } from './BlockMeta';
import {
  BlockMetaFromJSON,
  BlockMetaFromJSONTyped,
  BlockMetaToJSON,
  BlockMetaToJSONTyped,
} from './BlockMeta';

/**
 *
 * @export
 * @interface Metadata
 */
export interface Metadata {
  /**
   *
   * @type {BlockMeta}
   * @memberof Metadata
   */
  meta: BlockMeta;
  /**
   *
   * @type {boolean}
   * @memberof Metadata
   */
  readonly: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Metadata
   */
  deletable: boolean;
  /**
   *
   * @type {BlockMetadataType}
   * @memberof Metadata
   */
  type: BlockMetadataType;
}

/**
 * Check if a given object implements the Metadata interface.
 */
export function instanceOfMetadata(value: object): value is Metadata {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('readonly' in value) || value['readonly'] === undefined) return false;
  if (!('deletable' in value) || value['deletable'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  return true;
}

export function MetadataFromJSON(json: any): Metadata {
  return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
  if (json == null) {
    return json;
  }
  return {
    meta: BlockMetaFromJSON(json['meta']),
    readonly: json['readonly'],
    deletable: json['deletable'],
    type: BlockMetadataTypeFromJSON(json['type']),
  };
}

export function MetadataToJSON(json: any): Metadata {
  return MetadataToJSONTyped(json, false);
}

export function MetadataToJSONTyped(
  value?: Metadata | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: BlockMetaToJSON(value['meta']),
    readonly: value['readonly'],
    deletable: value['deletable'],
    type: BlockMetadataTypeToJSON(value['type']),
  };
}
