/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockEnvironment } from './BlockEnvironment';
import {
  BlockEnvironmentFromJSON,
  BlockEnvironmentFromJSONTyped,
  BlockEnvironmentToJSON,
  BlockEnvironmentToJSONTyped,
} from './BlockEnvironment';

/**
 *
 * @export
 * @interface OverwriteEnvironmentRequest
 */
export interface OverwriteEnvironmentRequest {
  /**
   *
   * @type {string}
   * @memberof OverwriteEnvironmentRequest
   */
  layoutId: string;
  /**
   *
   * @type {string}
   * @memberof OverwriteEnvironmentRequest
   */
  workspaceId: string;
  /**
   *
   * @type {number}
   * @memberof OverwriteEnvironmentRequest
   */
  version: number;
  /**
   *
   * @type {BlockEnvironment}
   * @memberof OverwriteEnvironmentRequest
   */
  environment: BlockEnvironment;
}

/**
 * Check if a given object implements the OverwriteEnvironmentRequest interface.
 */
export function instanceOfOverwriteEnvironmentRequest(
  value: object,
): value is OverwriteEnvironmentRequest {
  if (!('layoutId' in value) || value['layoutId'] === undefined) return false;
  if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('environment' in value) || value['environment'] === undefined) return false;
  return true;
}

export function OverwriteEnvironmentRequestFromJSON(json: any): OverwriteEnvironmentRequest {
  return OverwriteEnvironmentRequestFromJSONTyped(json, false);
}

export function OverwriteEnvironmentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OverwriteEnvironmentRequest {
  if (json == null) {
    return json;
  }
  return {
    layoutId: json['layoutId'],
    workspaceId: json['workspaceId'],
    version: json['version'],
    environment: BlockEnvironmentFromJSON(json['environment']),
  };
}

export function OverwriteEnvironmentRequestToJSON(json: any): OverwriteEnvironmentRequest {
  return OverwriteEnvironmentRequestToJSONTyped(json, false);
}

export function OverwriteEnvironmentRequestToJSONTyped(
  value?: OverwriteEnvironmentRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    layoutId: value['layoutId'],
    workspaceId: value['workspaceId'],
    version: value['version'],
    environment: BlockEnvironmentToJSON(value['environment']),
  };
}
