/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaveWorkflowNodeRequestConfig } from './SaveWorkflowNodeRequestConfig';
import {
  SaveWorkflowNodeRequestConfigFromJSON,
  SaveWorkflowNodeRequestConfigFromJSONTyped,
  SaveWorkflowNodeRequestConfigToJSON,
  SaveWorkflowNodeRequestConfigToJSONTyped,
} from './SaveWorkflowNodeRequestConfig';

/**
 *
 * @export
 * @interface SaveWorkflowNodeRequest
 */
export interface SaveWorkflowNodeRequest {
  /**
   *
   * @type {string}
   * @memberof SaveWorkflowNodeRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof SaveWorkflowNodeRequest
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof SaveWorkflowNodeRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SaveWorkflowNodeRequest
   */
  description?: string;
  /**
   *
   * @type {SaveWorkflowNodeRequestConfig}
   * @memberof SaveWorkflowNodeRequest
   */
  config: SaveWorkflowNodeRequestConfig;
}

/**
 * Check if a given object implements the SaveWorkflowNodeRequest interface.
 */
export function instanceOfSaveWorkflowNodeRequest(value: object): value is SaveWorkflowNodeRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function SaveWorkflowNodeRequestFromJSON(json: any): SaveWorkflowNodeRequest {
  return SaveWorkflowNodeRequestFromJSONTyped(json, false);
}

export function SaveWorkflowNodeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SaveWorkflowNodeRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    key: json['key'] == null ? undefined : json['key'],
    name: json['name'],
    description: json['description'] == null ? undefined : json['description'],
    config: SaveWorkflowNodeRequestConfigFromJSON(json['config']),
  };
}

export function SaveWorkflowNodeRequestToJSON(json: any): SaveWorkflowNodeRequest {
  return SaveWorkflowNodeRequestToJSONTyped(json, false);
}

export function SaveWorkflowNodeRequestToJSONTyped(
  value?: SaveWorkflowNodeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    key: value['key'],
    name: value['name'],
    description: value['description'],
    config: SaveWorkflowNodeRequestConfigToJSON(value['config']),
  };
}
