/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StructuralOperationRequest } from './StructuralOperationRequest';
import {
    StructuralOperationRequestFromJSON,
    StructuralOperationRequestFromJSONTyped,
    StructuralOperationRequestToJSON,
    StructuralOperationRequestToJSONTyped,
} from './StructuralOperationRequest';
import type { TreeLayout } from './TreeLayout';
import {
    TreeLayoutFromJSON,
    TreeLayoutFromJSONTyped,
    TreeLayoutToJSON,
    TreeLayoutToJSONTyped,
} from './TreeLayout';

/**
 * 
 * @export
 * @interface SaveEnvironmentRequest
 */
export interface SaveEnvironmentRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveEnvironmentRequest
     */
    layoutId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveEnvironmentRequest
     */
    workspaceId: string;
    /**
     * 
     * @type {TreeLayout}
     * @memberof SaveEnvironmentRequest
     */
    layout: TreeLayout;
    /**
     * 
     * @type {number}
     * @memberof SaveEnvironmentRequest
     */
    version: number;
    /**
     * 
     * @type {Array<StructuralOperationRequest>}
     * @memberof SaveEnvironmentRequest
     */
    operations: Array<StructuralOperationRequest>;
}

/**
 * Check if a given object implements the SaveEnvironmentRequest interface.
 */
export function instanceOfSaveEnvironmentRequest(value: object): value is SaveEnvironmentRequest {
    if (!('layoutId' in value) || value['layoutId'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('layout' in value) || value['layout'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function SaveEnvironmentRequestFromJSON(json: any): SaveEnvironmentRequest {
    return SaveEnvironmentRequestFromJSONTyped(json, false);
}

export function SaveEnvironmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveEnvironmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'layoutId': json['layoutId'],
        'workspaceId': json['workspaceId'],
        'layout': TreeLayoutFromJSON(json['layout']),
        'version': json['version'],
        'operations': ((json['operations'] as Array<any>).map(StructuralOperationRequestFromJSON)),
    };
}

export function SaveEnvironmentRequestToJSON(json: any): SaveEnvironmentRequest {
    return SaveEnvironmentRequestToJSONTyped(json, false);
}

export function SaveEnvironmentRequestToJSONTyped(value?: SaveEnvironmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layoutId': value['layoutId'],
        'workspaceId': value['workspaceId'],
        'layout': TreeLayoutToJSON(value['layout']),
        'version': value['version'],
        'operations': ((value['operations'] as Array<any>).map(StructuralOperationRequestToJSON)),
    };
}

