/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SaveAttributeDefinitionRequest } from './SaveAttributeDefinitionRequest';
import {
    instanceOfSaveAttributeDefinitionRequest,
    SaveAttributeDefinitionRequestFromJSON,
    SaveAttributeDefinitionRequestFromJSONTyped,
    SaveAttributeDefinitionRequestToJSON,
} from './SaveAttributeDefinitionRequest';
import type { SaveRelationshipDefinitionRequest } from './SaveRelationshipDefinitionRequest';
import {
    instanceOfSaveRelationshipDefinitionRequest,
    SaveRelationshipDefinitionRequestFromJSON,
    SaveRelationshipDefinitionRequestFromJSONTyped,
    SaveRelationshipDefinitionRequestToJSON,
} from './SaveRelationshipDefinitionRequest';

/**
 * @type SaveTypeDefinitionRequestDefinition
 * 
 * @export
 */
export type SaveTypeDefinitionRequestDefinition = SaveAttributeDefinitionRequest | SaveRelationshipDefinitionRequest;

export function SaveTypeDefinitionRequestDefinitionFromJSON(json: any): SaveTypeDefinitionRequestDefinition {
    return SaveTypeDefinitionRequestDefinitionFromJSONTyped(json, false);
}

export function SaveTypeDefinitionRequestDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveTypeDefinitionRequestDefinition {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfSaveAttributeDefinitionRequest(json)) {
        return SaveAttributeDefinitionRequestFromJSONTyped(json, true);
    }
    if (instanceOfSaveRelationshipDefinitionRequest(json)) {
        return SaveRelationshipDefinitionRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SaveTypeDefinitionRequestDefinitionToJSON(json: any): any {
    return SaveTypeDefinitionRequestDefinitionToJSONTyped(json, false);
}

export function SaveTypeDefinitionRequestDefinitionToJSONTyped(value?: SaveTypeDefinitionRequestDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfSaveAttributeDefinitionRequest(value)) {
        return SaveAttributeDefinitionRequestToJSON(value as SaveAttributeDefinitionRequest);
    }
    if (instanceOfSaveRelationshipDefinitionRequest(value)) {
        return SaveRelationshipDefinitionRequestToJSON(value as SaveRelationshipDefinitionRequest);
    }
    return {};
}

