/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IconType } from './IconType';
import {
    IconTypeFromJSON,
    IconTypeFromJSONTyped,
    IconTypeToJSON,
    IconTypeToJSONTyped,
} from './IconType';
import type { IconColour } from './IconColour';
import {
    IconColourFromJSON,
    IconColourFromJSONTyped,
    IconColourToJSON,
    IconColourToJSONTyped,
} from './IconColour';

/**
 * 
 * @export
 * @interface SaveWorkflowDefinitionRequest
 */
export interface SaveWorkflowDefinitionRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveWorkflowDefinitionRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveWorkflowDefinitionRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaveWorkflowDefinitionRequest
     */
    description?: string;
    /**
     * 
     * @type {IconColour}
     * @memberof SaveWorkflowDefinitionRequest
     */
    iconColour: IconColour;
    /**
     * 
     * @type {IconType}
     * @memberof SaveWorkflowDefinitionRequest
     */
    iconType: IconType;
    /**
     * 
     * @type {Array<string>}
     * @memberof SaveWorkflowDefinitionRequest
     */
    tags: Array<string>;
}



/**
 * Check if a given object implements the SaveWorkflowDefinitionRequest interface.
 */
export function instanceOfSaveWorkflowDefinitionRequest(value: object): value is SaveWorkflowDefinitionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconColour' in value) || value['iconColour'] === undefined) return false;
    if (!('iconType' in value) || value['iconType'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function SaveWorkflowDefinitionRequestFromJSON(json: any): SaveWorkflowDefinitionRequest {
    return SaveWorkflowDefinitionRequestFromJSONTyped(json, false);
}

export function SaveWorkflowDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWorkflowDefinitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'iconColour': IconColourFromJSON(json['iconColour']),
        'iconType': IconTypeFromJSON(json['iconType']),
        'tags': json['tags'],
    };
}

export function SaveWorkflowDefinitionRequestToJSON(json: any): SaveWorkflowDefinitionRequest {
    return SaveWorkflowDefinitionRequestToJSONTyped(json, false);
}

export function SaveWorkflowDefinitionRequestToJSONTyped(value?: SaveWorkflowDefinitionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'iconColour': IconColourToJSON(value['iconColour']),
        'iconType': IconTypeToJSON(value['iconType']),
        'tags': value['tags'],
    };
}

