/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataFormat } from './DataFormat';
import {
  DataFormatFromJSON,
  DataFormatFromJSONTyped,
  DataFormatToJSON,
  DataFormatToJSONTyped,
} from './DataFormat';
import type { DataType } from './DataType';
import {
  DataTypeFromJSON,
  DataTypeFromJSONTyped,
  DataTypeToJSON,
  DataTypeToJSONTyped,
} from './DataType';
import type { SchemaOptions } from './SchemaOptions';
import {
  SchemaOptionsFromJSON,
  SchemaOptionsFromJSONTyped,
  SchemaOptionsToJSON,
  SchemaOptionsToJSONTyped,
} from './SchemaOptions';
import type { Icon } from './Icon';
import { IconFromJSON, IconFromJSONTyped, IconToJSON, IconToJSONTyped } from './Icon';
import type { SchemaType } from './SchemaType';
import {
  SchemaTypeFromJSON,
  SchemaTypeFromJSONTyped,
  SchemaTypeToJSON,
  SchemaTypeToJSONTyped,
} from './SchemaType';

/**
 *
 * @export
 * @interface SchemaUUID
 */
export interface SchemaUUID {
  /**
   *
   * @type {string}
   * @memberof SchemaUUID
   */
  label?: string;
  /**
   *
   * @type {SchemaType}
   * @memberof SchemaUUID
   */
  key: SchemaType;
  /**
   *
   * @type {Icon}
   * @memberof SchemaUUID
   */
  icon: Icon;
  /**
   *
   * @type {DataType}
   * @memberof SchemaUUID
   */
  type: DataType;
  /**
   *
   * @type {DataFormat}
   * @memberof SchemaUUID
   */
  format?: DataFormat;
  /**
   *
   * @type {boolean}
   * @memberof SchemaUUID
   */
  required: boolean;
  /**
   *
   * @type {{ [key: string]: SchemaUUID; }}
   * @memberof SchemaUUID
   */
  properties?: { [key: string]: SchemaUUID };
  /**
   *
   * @type {SchemaUUID}
   * @memberof SchemaUUID
   */
  items?: SchemaUUID;
  /**
   *
   * @type {boolean}
   * @memberof SchemaUUID
   */
  unique: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SchemaUUID
   */
  _protected: boolean;
  /**
   *
   * @type {SchemaOptions}
   * @memberof SchemaUUID
   */
  options?: SchemaOptions;
}

/**
 * Check if a given object implements the SchemaUUID interface.
 */
export function instanceOfSchemaUUID(value: object): value is SchemaUUID {
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('icon' in value) || value['icon'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('required' in value) || value['required'] === undefined) return false;
  if (!('unique' in value) || value['unique'] === undefined) return false;
  if (!('_protected' in value) || value['_protected'] === undefined) return false;
  return true;
}

export function SchemaUUIDFromJSON(json: any): SchemaUUID {
  return SchemaUUIDFromJSONTyped(json, false);
}

export function SchemaUUIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaUUID {
  if (json == null) {
    return json;
  }
  return {
    label: json['label'] == null ? undefined : json['label'],
    key: SchemaTypeFromJSON(json['key']),
    icon: IconFromJSON(json['icon']),
    type: DataTypeFromJSON(json['type']),
    format: json['format'] == null ? undefined : DataFormatFromJSON(json['format']),
    required: json['required'],
    properties:
      json['properties'] == null ? undefined : mapValues(json['properties'], SchemaUUIDFromJSON),
    items: json['items'] == null ? undefined : SchemaUUIDFromJSON(json['items']),
    unique: json['unique'],
    _protected: json['protected'],
    options: json['options'] == null ? undefined : SchemaOptionsFromJSON(json['options']),
  };
}

export function SchemaUUIDToJSON(json: any): SchemaUUID {
  return SchemaUUIDToJSONTyped(json, false);
}

export function SchemaUUIDToJSONTyped(
  value?: SchemaUUID | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    label: value['label'],
    key: SchemaTypeToJSON(value['key']),
    icon: IconToJSON(value['icon']),
    type: DataTypeToJSON(value['type']),
    format: DataFormatToJSON(value['format']),
    required: value['required'],
    properties:
      value['properties'] == null ? undefined : mapValues(value['properties'], SchemaUUIDToJSON),
    items: SchemaUUIDToJSON(value['items']),
    unique: value['unique'],
    protected: value['_protected'],
    options: SchemaOptionsToJSON(value['options']),
  };
}
