/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type TreeLayoutColumn
 * Number of columns or the string 'auto'
 * @export
 */
export type TreeLayoutColumn = number | string;

export function TreeLayoutColumnFromJSON(json: any): TreeLayoutColumn {
    return TreeLayoutColumnFromJSONTyped(json, false);
}

export function TreeLayoutColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeLayoutColumn {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function TreeLayoutColumnToJSON(json: any): any {
    return TreeLayoutColumnToJSONTyped(json, false);
}

export function TreeLayoutColumnToJSONTyped(value?: TreeLayoutColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

