/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityTypeRequestDefinition } from './EntityTypeRequestDefinition';
import {
    EntityTypeRequestDefinitionFromJSON,
    EntityTypeRequestDefinitionFromJSONTyped,
    EntityTypeRequestDefinitionToJSON,
    EntityTypeRequestDefinitionToJSONTyped,
} from './EntityTypeRequestDefinition';

/**
 * 
 * @export
 * @interface TypeDefinition
 */
export interface TypeDefinition {
    /**
     * 
     * @type {string}
     * @memberof TypeDefinition
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof TypeDefinition
     */
    id: string;
    /**
     * 
     * @type {EntityTypeRequestDefinition}
     * @memberof TypeDefinition
     */
    type: EntityTypeRequestDefinition;
}



/**
 * Check if a given object implements the TypeDefinition interface.
 */
export function instanceOfTypeDefinition(value: object): value is TypeDefinition {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypeDefinitionFromJSON(json: any): TypeDefinition {
    return TypeDefinitionFromJSONTyped(json, false);
}

export function TypeDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'id': json['id'],
        'type': EntityTypeRequestDefinitionFromJSON(json['type']),
    };
}

export function TypeDefinitionToJSON(json: any): TypeDefinition {
    return TypeDefinitionToJSONTyped(json, false);
}

export function TypeDefinitionToJSONTyped(value?: TypeDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'id': value['id'],
        'type': EntityTypeRequestDefinitionToJSON(value['type']),
    };
}

