/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserDisplay
 */
export interface UserDisplay {
  /**
   *
   * @type {string}
   * @memberof UserDisplay
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UserDisplay
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserDisplay
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserDisplay
   */
  avatarUrl?: string;
}

/**
 * Check if a given object implements the UserDisplay interface.
 */
export function instanceOfUserDisplay(value: object): value is UserDisplay {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function UserDisplayFromJSON(json: any): UserDisplay {
  return UserDisplayFromJSONTyped(json, false);
}

export function UserDisplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDisplay {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    name: json['name'],
    avatarUrl: json['avatarUrl'] == null ? undefined : json['avatarUrl'],
  };
}

export function UserDisplayToJSON(json: any): UserDisplay {
  return UserDisplayToJSONTyped(json, false);
}

export function UserDisplayToJSONTyped(
  value?: UserDisplay | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    name: value['name'],
    avatarUrl: value['avatarUrl'],
  };
}
