/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Operand } from './Operand';
import {
  OperandFromJSON,
  OperandFromJSONTyped,
  OperandToJSON,
  OperandToJSONTyped,
} from './Operand';

/**
 *
 * @export
 * @interface Value
 */
export interface Value extends Operand {
  /**
   *
   * @type {object}
   * @memberof Value
   */
  value?: object;
}

/**
 * Check if a given object implements the Value interface.
 */
export function instanceOfValue(value: object): value is Value {
  return true;
}

export function ValueFromJSON(json: any): Value {
  return ValueFromJSONTyped(json, false);
}

export function ValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Value {
  if (json == null) {
    return json;
  }
  return {
    ...OperandFromJSONTyped(json, true),
    value: json['value'] == null ? undefined : json['value'],
  };
}

export function ValueToJSON(json: any): Value {
  return ValueToJSONTyped(json, false);
}

export function ValueToJSONTyped(value?: Value | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    ...OperandToJSONTyped(value, true),
    value: value['value'],
  };
}
