/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';

/**
 * Configuration for FUNCTION category nodes.
 * @export
 * @interface WorkflowFunctionConfig
 */
export interface WorkflowFunctionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowFunctionConfig
     */
    version?: number;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowFunctionConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowFunctionConfig interface.
 */
export function instanceOfWorkflowFunctionConfig(value: object): value is WorkflowFunctionConfig {
    return true;
}

export function WorkflowFunctionConfigFromJSON(json: any): WorkflowFunctionConfig {
    return WorkflowFunctionConfigFromJSONTyped(json, false);
}

export function WorkflowFunctionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowFunctionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowFunctionConfigToJSON(json: any): WorkflowFunctionConfig {
    return WorkflowFunctionConfigToJSONTyped(json, false);
}

export function WorkflowFunctionConfigToJSONTyped(value?: WorkflowFunctionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

