/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WorkflowUtilityActionType = {
    Log: 'LOG',
    Notify: 'NOTIFY',
    Validate: 'VALIDATE',
    ThrowError: 'THROW_ERROR'
} as const;
export type WorkflowUtilityActionType = typeof WorkflowUtilityActionType[keyof typeof WorkflowUtilityActionType];


export function instanceOfWorkflowUtilityActionType(value: any): boolean {
    for (const key in WorkflowUtilityActionType) {
        if (Object.prototype.hasOwnProperty.call(WorkflowUtilityActionType, key)) {
            if (WorkflowUtilityActionType[key as keyof typeof WorkflowUtilityActionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkflowUtilityActionTypeFromJSON(json: any): WorkflowUtilityActionType {
    return WorkflowUtilityActionTypeFromJSONTyped(json, false);
}

export function WorkflowUtilityActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowUtilityActionType {
    return json as WorkflowUtilityActionType;
}

export function WorkflowUtilityActionTypeToJSON(value?: WorkflowUtilityActionType | null): any {
    return value as any;
}

export function WorkflowUtilityActionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowUtilityActionType {
    return value as WorkflowUtilityActionType;
}

