/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowGraph } from './WorkflowGraph';
import {
    WorkflowGraphFromJSON,
    WorkflowGraphFromJSONTyped,
    WorkflowGraphToJSON,
    WorkflowGraphToJSONTyped,
} from './WorkflowGraph';

/**
 * 
 * @export
 * @interface WorkflowDefinitionVersion
 */
export interface WorkflowDefinitionVersion {
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinitionVersion
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowDefinitionVersion
     */
    version: number;
    /**
     * 
     * @type {WorkflowGraph}
     * @memberof WorkflowDefinitionVersion
     */
    workflow?: WorkflowGraph;
    /**
     * 
     * @type {object}
     * @memberof WorkflowDefinitionVersion
     */
    canvas: object;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDefinitionVersion
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDefinitionVersion
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinitionVersion
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinitionVersion
     */
    updatedBy?: string;
}

/**
 * Check if a given object implements the WorkflowDefinitionVersion interface.
 */
export function instanceOfWorkflowDefinitionVersion(value: object): value is WorkflowDefinitionVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('canvas' in value) || value['canvas'] === undefined) return false;
    return true;
}

export function WorkflowDefinitionVersionFromJSON(json: any): WorkflowDefinitionVersion {
    return WorkflowDefinitionVersionFromJSONTyped(json, false);
}

export function WorkflowDefinitionVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDefinitionVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': json['version'],
        'workflow': json['workflow'] == null ? undefined : WorkflowGraphFromJSON(json['workflow']),
        'canvas': json['canvas'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
    };
}

export function WorkflowDefinitionVersionToJSON(json: any): WorkflowDefinitionVersion {
    return WorkflowDefinitionVersionToJSONTyped(json, false);
}

export function WorkflowDefinitionVersionToJSONTyped(value?: WorkflowDefinitionVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'workflow': WorkflowGraphToJSON(value['workflow']),
        'canvas': value['canvas'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
    };
}

