/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowActionType } from './WorkflowActionType';
import {
    WorkflowActionTypeFromJSON,
    WorkflowActionTypeFromJSONTyped,
    WorkflowActionTypeToJSON,
    WorkflowActionTypeToJSONTyped,
} from './WorkflowActionType';

/**
 * Configuration for HTTP_REQUEST action nodes.
 * @export
 * @interface WorkflowHttpRequestActionConfig
 */
export interface WorkflowHttpRequestActionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowHttpRequestActionConfig
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowHttpRequestActionConfig
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowHttpRequestActionConfig
     */
    config?: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowActionType}
     * @memberof WorkflowHttpRequestActionConfig
     */
    subType?: WorkflowActionType;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowHttpRequestActionConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowHttpRequestActionConfig interface.
 */
export function instanceOfWorkflowHttpRequestActionConfig(value: object): value is WorkflowHttpRequestActionConfig {
    return true;
}

export function WorkflowHttpRequestActionConfigFromJSON(json: any): WorkflowHttpRequestActionConfig {
    return WorkflowHttpRequestActionConfigFromJSONTyped(json, false);
}

export function WorkflowHttpRequestActionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowHttpRequestActionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'name': json['name'] == null ? undefined : json['name'],
        'config': json['config'] == null ? undefined : json['config'],
        'subType': json['subType'] == null ? undefined : WorkflowActionTypeFromJSON(json['subType']),
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowHttpRequestActionConfigToJSON(json: any): WorkflowHttpRequestActionConfig {
    return WorkflowHttpRequestActionConfigToJSONTyped(json, false);
}

export function WorkflowHttpRequestActionConfigToJSONTyped(value?: WorkflowHttpRequestActionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'name': value['name'],
        'config': value['config'],
        'subType': WorkflowActionTypeToJSON(value['subType']),
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

