/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowControlType } from './WorkflowControlType';
import {
    WorkflowControlTypeFromJSON,
    WorkflowControlTypeFromJSONTyped,
    WorkflowControlTypeToJSON,
    WorkflowControlTypeToJSONTyped,
} from './WorkflowControlType';

/**
 * Configuration for CONDITION control flow nodes.
 * @export
 * @interface WorkflowConditionControlConfig
 */
export interface WorkflowConditionControlConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowConditionControlConfig
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowConditionControlConfig
     */
    expression?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowConditionControlConfig
     */
    contextEntityId?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowConditionControlConfig
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {WorkflowControlType}
     * @memberof WorkflowConditionControlConfig
     */
    subType?: WorkflowControlType;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowConditionControlConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowConditionControlConfig interface.
 */
export function instanceOfWorkflowConditionControlConfig(value: object): value is WorkflowConditionControlConfig {
    return true;
}

export function WorkflowConditionControlConfigFromJSON(json: any): WorkflowConditionControlConfig {
    return WorkflowConditionControlConfigFromJSONTyped(json, false);
}

export function WorkflowConditionControlConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowConditionControlConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'expression': json['expression'] == null ? undefined : json['expression'],
        'contextEntityId': json['contextEntityId'] == null ? undefined : json['contextEntityId'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'subType': json['subType'] == null ? undefined : WorkflowControlTypeFromJSON(json['subType']),
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowConditionControlConfigToJSON(json: any): WorkflowConditionControlConfig {
    return WorkflowConditionControlConfigToJSONTyped(json, false);
}

export function WorkflowConditionControlConfigToJSONTyped(value?: WorkflowConditionControlConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'expression': value['expression'],
        'contextEntityId': value['contextEntityId'],
        'timeoutSeconds': value['timeoutSeconds'],
        'subType': WorkflowControlTypeToJSON(value['subType']),
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

