/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum WorkspaceInviteStatus {
    Pending = 'PENDING',
    Accepted = 'ACCEPTED',
    Declined = 'DECLINED',
    Expired = 'EXPIRED'
}


export function instanceOfWorkspaceInviteStatus(value: any): boolean {
    for (const key in WorkspaceInviteStatus) {
        if (Object.prototype.hasOwnProperty.call(WorkspaceInviteStatus, key)) {
            if (WorkspaceInviteStatus[key as keyof typeof WorkspaceInviteStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkspaceInviteStatusFromJSON(json: any): WorkspaceInviteStatus {
    return WorkspaceInviteStatusFromJSONTyped(json, false);
}

export function WorkspaceInviteStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceInviteStatus {
    return json as WorkspaceInviteStatus;
}

export function WorkspaceInviteStatusToJSON(value?: WorkspaceInviteStatus | null): any {
    return value as any;
}

export function WorkspaceInviteStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkspaceInviteStatus {
    return value as WorkspaceInviteStatus;
}

