/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowDefinitionStatus } from './WorkflowDefinitionStatus';
import {
    WorkflowDefinitionStatusFromJSON,
    WorkflowDefinitionStatusFromJSONTyped,
    WorkflowDefinitionStatusToJSON,
    WorkflowDefinitionStatusToJSONTyped,
} from './WorkflowDefinitionStatus';
import type { WorkflowDefinitionVersion } from './WorkflowDefinitionVersion';
import {
    WorkflowDefinitionVersionFromJSON,
    WorkflowDefinitionVersionFromJSONTyped,
    WorkflowDefinitionVersionToJSON,
    WorkflowDefinitionVersionToJSONTyped,
} from './WorkflowDefinitionVersion';
import type { Icon } from './Icon';
import {
    IconFromJSON,
    IconFromJSONTyped,
    IconToJSON,
    IconToJSONTyped,
} from './Icon';

/**
 * 
 * @export
 * @interface WorkflowDefinition
 */
export interface WorkflowDefinition {
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    description?: string;
    /**
     * 
     * @type {WorkflowDefinitionStatus}
     * @memberof WorkflowDefinition
     */
    status: WorkflowDefinitionStatus;
    /**
     * 
     * @type {Icon}
     * @memberof WorkflowDefinition
     */
    icon: Icon;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowDefinition
     */
    tags: Array<string>;
    /**
     * 
     * @type {WorkflowDefinitionVersion}
     * @memberof WorkflowDefinition
     */
    definition: WorkflowDefinitionVersion;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDefinition
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDefinition
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    updatedBy?: string;
}



/**
 * Check if a given object implements the WorkflowDefinition interface.
 */
export function instanceOfWorkflowDefinition(value: object): value is WorkflowDefinition {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('definition' in value) || value['definition'] === undefined) return false;
    return true;
}

export function WorkflowDefinitionFromJSON(json: any): WorkflowDefinition {
    return WorkflowDefinitionFromJSONTyped(json, false);
}

export function WorkflowDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': WorkflowDefinitionStatusFromJSON(json['status']),
        'icon': IconFromJSON(json['icon']),
        'tags': json['tags'],
        'definition': WorkflowDefinitionVersionFromJSON(json['definition']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
    };
}

export function WorkflowDefinitionToJSON(json: any): WorkflowDefinition {
    return WorkflowDefinitionToJSONTyped(json, false);
}

export function WorkflowDefinitionToJSONTyped(value?: WorkflowDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'name': value['name'],
        'description': value['description'],
        'status': WorkflowDefinitionStatusToJSON(value['status']),
        'icon': IconToJSON(value['icon']),
        'tags': value['tags'],
        'definition': WorkflowDefinitionVersionToJSON(value['definition']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
    };
}

