/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowActionType } from './WorkflowActionType';
import {
    WorkflowActionTypeFromJSON,
    WorkflowActionTypeFromJSONTyped,
    WorkflowActionTypeToJSON,
    WorkflowActionTypeToJSONTyped,
} from './WorkflowActionType';

/**
 * Configuration for UPDATE_ENTITY action nodes.
 * @export
 * @interface WorkflowUpdateEntityActionConfig
 */
export interface WorkflowUpdateEntityActionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    entityId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    payload?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    config?: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowActionType}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    subType?: WorkflowActionType;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowUpdateEntityActionConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowUpdateEntityActionConfig interface.
 */
export function instanceOfWorkflowUpdateEntityActionConfig(value: object): value is WorkflowUpdateEntityActionConfig {
    return true;
}

export function WorkflowUpdateEntityActionConfigFromJSON(json: any): WorkflowUpdateEntityActionConfig {
    return WorkflowUpdateEntityActionConfigFromJSONTyped(json, false);
}

export function WorkflowUpdateEntityActionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowUpdateEntityActionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'config': json['config'] == null ? undefined : json['config'],
        'subType': json['subType'] == null ? undefined : WorkflowActionTypeFromJSON(json['subType']),
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowUpdateEntityActionConfigToJSON(json: any): WorkflowUpdateEntityActionConfig {
    return WorkflowUpdateEntityActionConfigToJSONTyped(json, false);
}

export function WorkflowUpdateEntityActionConfigToJSONTyped(value?: WorkflowUpdateEntityActionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'entityId': value['entityId'],
        'payload': value['payload'],
        'timeoutSeconds': value['timeoutSeconds'],
        'config': value['config'],
        'subType': WorkflowActionTypeToJSON(value['subType']),
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

