/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowScheduleTriggerConfigIntervalUnitsInner
 */
export interface WorkflowScheduleTriggerConfigIntervalUnitsInner {
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowScheduleTriggerConfigIntervalUnitsInner
     */
    durationEstimated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowScheduleTriggerConfigIntervalUnitsInner
     */
    timeBased?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowScheduleTriggerConfigIntervalUnitsInner
     */
    dateBased?: boolean;
}

/**
 * Check if a given object implements the WorkflowScheduleTriggerConfigIntervalUnitsInner interface.
 */
export function instanceOfWorkflowScheduleTriggerConfigIntervalUnitsInner(value: object): value is WorkflowScheduleTriggerConfigIntervalUnitsInner {
    return true;
}

export function WorkflowScheduleTriggerConfigIntervalUnitsInnerFromJSON(json: any): WorkflowScheduleTriggerConfigIntervalUnitsInner {
    return WorkflowScheduleTriggerConfigIntervalUnitsInnerFromJSONTyped(json, false);
}

export function WorkflowScheduleTriggerConfigIntervalUnitsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowScheduleTriggerConfigIntervalUnitsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'durationEstimated': json['durationEstimated'] == null ? undefined : json['durationEstimated'],
        'timeBased': json['timeBased'] == null ? undefined : json['timeBased'],
        'dateBased': json['dateBased'] == null ? undefined : json['dateBased'],
    };
}

export function WorkflowScheduleTriggerConfigIntervalUnitsInnerToJSON(json: any): WorkflowScheduleTriggerConfigIntervalUnitsInner {
    return WorkflowScheduleTriggerConfigIntervalUnitsInnerToJSONTyped(json, false);
}

export function WorkflowScheduleTriggerConfigIntervalUnitsInnerToJSONTyped(value?: WorkflowScheduleTriggerConfigIntervalUnitsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'durationEstimated': value['durationEstimated'],
        'timeBased': value['timeBased'],
        'dateBased': value['dateBased'],
    };
}

