/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaString } from './SchemaString';
import {
    SchemaStringFromJSON,
    SchemaStringFromJSONTyped,
    SchemaStringToJSON,
    SchemaStringToJSONTyped,
} from './SchemaString';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowTriggerType } from './WorkflowTriggerType';
import {
    WorkflowTriggerTypeFromJSON,
    WorkflowTriggerTypeFromJSONTyped,
    WorkflowTriggerTypeToJSON,
    WorkflowTriggerTypeToJSONTyped,
} from './WorkflowTriggerType';

/**
 * Configuration for FUNCTION trigger nodes. Triggers workflow execution when called as a function.
 * @export
 * @interface WorkflowFunctionTriggerConfig
 */
export interface WorkflowFunctionTriggerConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowFunctionTriggerConfig
     */
    version?: number;
    /**
     * 
     * @type {SchemaString}
     * @memberof WorkflowFunctionTriggerConfig
     */
    schema?: SchemaString;
    /**
     * 
     * @type {WorkflowTriggerType}
     * @memberof WorkflowFunctionTriggerConfig
     */
    subType?: WorkflowTriggerType;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowFunctionTriggerConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowFunctionTriggerConfig interface.
 */
export function instanceOfWorkflowFunctionTriggerConfig(value: object): value is WorkflowFunctionTriggerConfig {
    return true;
}

export function WorkflowFunctionTriggerConfigFromJSON(json: any): WorkflowFunctionTriggerConfig {
    return WorkflowFunctionTriggerConfigFromJSONTyped(json, false);
}

export function WorkflowFunctionTriggerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowFunctionTriggerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'schema': json['schema'] == null ? undefined : SchemaStringFromJSON(json['schema']),
        'subType': json['subType'] == null ? undefined : WorkflowTriggerTypeFromJSON(json['subType']),
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowFunctionTriggerConfigToJSON(json: any): WorkflowFunctionTriggerConfig {
    return WorkflowFunctionTriggerConfigToJSONTyped(json, false);
}

export function WorkflowFunctionTriggerConfigToJSONTyped(value?: WorkflowFunctionTriggerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'schema': SchemaStringToJSON(value['schema']),
        'subType': WorkflowTriggerTypeToJSON(value['subType']),
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

