/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchDeleteRequest
 */
export interface BatchDeleteRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchDeleteRequest
     */
    fileIds: Array<string>;
}

/**
 * Check if a given object implements the BatchDeleteRequest interface.
 */
export function instanceOfBatchDeleteRequest(value: object): value is BatchDeleteRequest {
    if (!('fileIds' in value) || value['fileIds'] === undefined) return false;
    return true;
}

export function BatchDeleteRequestFromJSON(json: any): BatchDeleteRequest {
    return BatchDeleteRequestFromJSONTyped(json, false);
}

export function BatchDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileIds': json['fileIds'],
    };
}

export function BatchDeleteRequestToJSON(json: any): BatchDeleteRequest {
    return BatchDeleteRequestToJSONTyped(json, false);
}

export function BatchDeleteRequestToJSONTyped(value?: BatchDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileIds': value['fileIds'],
    };
}

