/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enumeration of possible block operation types for requests.
 * @export
 * @enum {string}
 */
export enum BlockOperationType {
    AddBlock = 'ADD_BLOCK',
    RemoveBlock = 'REMOVE_BLOCK',
    MoveBlock = 'MOVE_BLOCK',
    UpdateBlock = 'UPDATE_BLOCK',
    ReorderBlock = 'REORDER_BLOCK'
}


export function instanceOfBlockOperationType(value: any): boolean {
    for (const key in BlockOperationType) {
        if (Object.prototype.hasOwnProperty.call(BlockOperationType, key)) {
            if (BlockOperationType[key as keyof typeof BlockOperationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlockOperationTypeFromJSON(json: any): BlockOperationType {
    return BlockOperationTypeFromJSONTyped(json, false);
}

export function BlockOperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockOperationType {
    return json as BlockOperationType;
}

export function BlockOperationTypeToJSON(value?: BlockOperationType | null): any {
    return value as any;
}

export function BlockOperationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BlockOperationType {
    return value as BlockOperationType;
}

