/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Error handling mode for individual entity update failures.
 * @export
 * @enum {string}
 */
export enum BulkUpdateErrorHandling {
    FailFast = 'FAIL_FAST',
    BestEffort = 'BEST_EFFORT'
}


export function instanceOfBulkUpdateErrorHandling(value: any): boolean {
    for (const key in BulkUpdateErrorHandling) {
        if (Object.prototype.hasOwnProperty.call(BulkUpdateErrorHandling, key)) {
            if (BulkUpdateErrorHandling[key as keyof typeof BulkUpdateErrorHandling] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BulkUpdateErrorHandlingFromJSON(json: any): BulkUpdateErrorHandling {
    return BulkUpdateErrorHandlingFromJSONTyped(json, false);
}

export function BulkUpdateErrorHandlingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateErrorHandling {
    return json as BulkUpdateErrorHandling;
}

export function BulkUpdateErrorHandlingToJSON(value?: BulkUpdateErrorHandling | null): any {
    return value as any;
}

export function BulkUpdateErrorHandlingToJSONTyped(value: any, ignoreDiscriminator: boolean): BulkUpdateErrorHandling {
    return value as BulkUpdateErrorHandling;
}

