/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleTemplatePreview } from './BundleTemplatePreview';
import {
    BundleTemplatePreviewFromJSON,
    BundleTemplatePreviewFromJSONTyped,
    BundleTemplatePreviewToJSON,
    BundleTemplatePreviewToJSONTyped,
} from './BundleTemplatePreview';

/**
 * 
 * @export
 * @interface BundlePreview
 */
export interface BundlePreview {
    /**
     * 
     * @type {string}
     * @memberof BundlePreview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BundlePreview
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof BundlePreview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BundlePreview
     */
    description?: string;
    /**
     * 
     * @type {Array<BundleTemplatePreview>}
     * @memberof BundlePreview
     */
    templates: Array<BundleTemplatePreview>;
}

/**
 * Check if a given object implements the BundlePreview interface.
 */
export function instanceOfBundlePreview(value: object): value is BundlePreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function BundlePreviewFromJSON(json: any): BundlePreview {
    return BundlePreviewFromJSONTyped(json, false);
}

export function BundlePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlePreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'templates': ((json['templates'] as Array<any>).map(BundleTemplatePreviewFromJSON)),
    };
}

export function BundlePreviewToJSON(json: any): BundlePreview {
    return BundlePreviewToJSONTyped(json, false);
}

export function BundlePreviewToJSONTyped(value?: BundlePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'description': value['description'],
        'templates': ((value['templates'] as Array<any>).map(BundleTemplatePreviewToJSON)),
    };
}

