/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessDefinitionResult
 */
export interface BusinessDefinitionResult {
    /**
     * 
     * @type {string}
     * @memberof BusinessDefinitionResult
     */
    term: string;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessDefinitionResult
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof BusinessDefinitionResult
     */
    error?: string;
}

/**
 * Check if a given object implements the BusinessDefinitionResult interface.
 */
export function instanceOfBusinessDefinitionResult(value: object): value is BusinessDefinitionResult {
    if (!('term' in value) || value['term'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function BusinessDefinitionResultFromJSON(json: any): BusinessDefinitionResult {
    return BusinessDefinitionResultFromJSONTyped(json, false);
}

export function BusinessDefinitionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessDefinitionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'term': json['term'],
        'success': json['success'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function BusinessDefinitionResultToJSON(json: any): BusinessDefinitionResult {
    return BusinessDefinitionResultToJSONTyped(json, false);
}

export function BusinessDefinitionResultToJSONTyped(value?: BusinessDefinitionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'term': value['term'],
        'success': value['success'],
        'error': value['error'],
    };
}

