/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BusinessType {
    DtcEcommerce = 'DTC_ECOMMERCE',
    B2CSaas = 'B2C_SAAS'
}


export function instanceOfBusinessType(value: any): boolean {
    for (const key in BusinessType) {
        if (Object.prototype.hasOwnProperty.call(BusinessType, key)) {
            if (BusinessType[key as keyof typeof BusinessType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BusinessTypeFromJSON(json: any): BusinessType {
    return BusinessTypeFromJSONTyped(json, false);
}

export function BusinessTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessType {
    return json as BusinessType;
}

export function BusinessTypeToJSON(value?: BusinessType | null): any {
    return value as any;
}

export function BusinessTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BusinessType {
    return value as BusinessType;
}

