/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterSummaryResponse
 */
export interface ClusterSummaryResponse {
    /**
     * 
     * @type {string}
     * @memberof ClusterSummaryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterSummaryResponse
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterSummaryResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterSummaryResponse
     */
    memberCount: number;
    /**
     * 
     * @type {Date}
     * @memberof ClusterSummaryResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ClusterSummaryResponse interface.
 */
export function instanceOfClusterSummaryResponse(value: object): value is ClusterSummaryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ClusterSummaryResponseFromJSON(json: any): ClusterSummaryResponse {
    return ClusterSummaryResponseFromJSONTyped(json, false);
}

export function ClusterSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'name': json['name'] == null ? undefined : json['name'],
        'memberCount': json['memberCount'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ClusterSummaryResponseToJSON(json: any): ClusterSummaryResponse {
    return ClusterSummaryResponseToJSONTyped(json, false);
}

export function ClusterSummaryResponseToJSONTyped(value?: ClusterSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'name': value['name'],
        'memberCount': value['memberCount'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

