/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnOverride } from './ColumnOverride';
import {
    ColumnOverrideFromJSON,
    ColumnOverrideFromJSONTyped,
    ColumnOverrideToJSON,
    ColumnOverrideToJSONTyped,
} from './ColumnOverride';

/**
 * 
 * @export
 * @interface ColumnConfiguration
 */
export interface ColumnConfiguration {
    /**
     * 
     * @type {Array<string>}
     * @memberof ColumnConfiguration
     */
    order: Array<string>;
    /**
     * 
     * @type {{ [key: string]: ColumnOverride; }}
     * @memberof ColumnConfiguration
     */
    overrides: { [key: string]: ColumnOverride; };
}

/**
 * Check if a given object implements the ColumnConfiguration interface.
 */
export function instanceOfColumnConfiguration(value: object): value is ColumnConfiguration {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('overrides' in value) || value['overrides'] === undefined) return false;
    return true;
}

export function ColumnConfigurationFromJSON(json: any): ColumnConfiguration {
    return ColumnConfigurationFromJSONTyped(json, false);
}

export function ColumnConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'],
        'overrides': (mapValues(json['overrides'], ColumnOverrideFromJSON)),
    };
}

export function ColumnConfigurationToJSON(json: any): ColumnConfiguration {
    return ColumnConfigurationToJSONTyped(json, false);
}

export function ColumnConfigurationToJSONTyped(value?: ColumnConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order': value['order'],
        'overrides': (mapValues(value['overrides'], ColumnOverrideToJSON)),
    };
}

