/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Op } from './Op';
import {
    OpFromJSON,
    OpFromJSONTyped,
    OpToJSON,
    OpToJSONTyped,
} from './Op';
import type { ConditionLeft } from './ConditionLeft';
import {
    ConditionLeftFromJSON,
    ConditionLeftFromJSONTyped,
    ConditionLeftToJSON,
    ConditionLeftToJSONTyped,
} from './ConditionLeft';

/**
 * 
 * @export
 * @interface Condition
 */
export interface Condition {
    /**
     * 
     * @type {Op}
     * @memberof Condition
     */
    op: Op;
    /**
     * 
     * @type {ConditionLeft}
     * @memberof Condition
     */
    left: ConditionLeft;
    /**
     * 
     * @type {ConditionLeft}
     * @memberof Condition
     */
    right?: ConditionLeft;
}



/**
 * Check if a given object implements the Condition interface.
 */
export function instanceOfCondition(value: object): value is Condition {
    if (!('op' in value) || value['op'] === undefined) return false;
    if (!('left' in value) || value['left'] === undefined) return false;
    return true;
}

export function ConditionFromJSON(json: any): Condition {
    return ConditionFromJSONTyped(json, false);
}

export function ConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Condition {
    if (json == null) {
        return json;
    }
    return {
        
        'op': OpFromJSON(json['op']),
        'left': ConditionLeftFromJSON(json['left']),
        'right': json['right'] == null ? undefined : ConditionLeftFromJSON(json['right']),
    };
}

export function ConditionToJSON(json: any): Condition {
    return ConditionToJSONTyped(json, false);
}

export function ConditionToJSONTyped(value?: Condition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'op': OpToJSON(value['op']),
        'left': ConditionLeftToJSON(value['left']),
        'right': ConditionLeftToJSON(value['right']),
    };
}

