/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmUploadRequest
 */
export interface ConfirmUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmUploadRequest
     */
    storageKey: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmUploadRequest
     */
    originalFilename: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConfirmUploadRequest
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ConfirmUploadRequest interface.
 */
export function instanceOfConfirmUploadRequest(value: object): value is ConfirmUploadRequest {
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('originalFilename' in value) || value['originalFilename'] === undefined) return false;
    return true;
}

export function ConfirmUploadRequestFromJSON(json: any): ConfirmUploadRequest {
    return ConfirmUploadRequestFromJSONTyped(json, false);
}

export function ConfirmUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKey': json['storageKey'],
        'originalFilename': json['originalFilename'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ConfirmUploadRequestToJSON(json: any): ConfirmUploadRequest {
    return ConfirmUploadRequestToJSONTyped(json, false);
}

export function ConfirmUploadRequestToJSONTyped(value?: ConfirmUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageKey': value['storageKey'],
        'originalFilename': value['originalFilename'],
        'metadata': value['metadata'],
    };
}

