/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConnectionStatus {
    Connected = 'CONNECTED',
    Syncing = 'SYNCING',
    Healthy = 'HEALTHY',
    Degraded = 'DEGRADED',
    Stale = 'STALE',
    Disconnecting = 'DISCONNECTING',
    Disconnected = 'DISCONNECTED',
    Failed = 'FAILED'
}


export function instanceOfConnectionStatus(value: any): boolean {
    for (const key in ConnectionStatus) {
        if (Object.prototype.hasOwnProperty.call(ConnectionStatus, key)) {
            if (ConnectionStatus[key as keyof typeof ConnectionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConnectionStatusFromJSON(json: any): ConnectionStatus {
    return ConnectionStatusFromJSONTyped(json, false);
}

export function ConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionStatus {
    return json as ConnectionStatus;
}

export function ConnectionStatusToJSON(value?: ConnectionStatus | null): any {
    return value as any;
}

export function ConnectionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ConnectionStatus {
    return value as ConnectionStatus;
}

