/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferencePayload } from './ReferencePayload';
import {
    ReferencePayloadFromJSON,
    ReferencePayloadFromJSONTyped,
    ReferencePayloadToJSON,
    ReferencePayloadToJSONTyped,
} from './ReferencePayload';
import type { NodeType } from './NodeType';
import {
    NodeTypeFromJSON,
    NodeTypeFromJSONTyped,
    NodeTypeToJSON,
    NodeTypeToJSONTyped,
} from './NodeType';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
    BlockToJSONTyped,
} from './Block';

/**
 * Content node containing a block with optional children
 * @export
 * @interface ContentNode
 */
export interface ContentNode {
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentNode
     */
    warnings: Array<string>;
    /**
     * 
     * @type {NodeType}
     * @memberof ContentNode
     */
    type: NodeType;
    /**
     * 
     * @type {Block}
     * @memberof ContentNode
     */
    block: Block;
    /**
     * 
     * @type {Array<object>}
     * @memberof ContentNode
     */
    children?: Array<object> | null;
    /**
     * 
     * @type {ReferencePayload}
     * @memberof ContentNode
     */
    reference: ReferencePayload;
}



/**
 * Check if a given object implements the ContentNode interface.
 */
export function instanceOfContentNode(value: object): value is ContentNode {
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('block' in value) || value['block'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function ContentNodeFromJSON(json: any): ContentNode {
    return ContentNodeFromJSONTyped(json, false);
}

export function ContentNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentNode {
    if (json == null) {
        return json;
    }
    return {
        
        'warnings': json['warnings'],
        'type': NodeTypeFromJSON(json['type']),
        'block': BlockFromJSON(json['block']),
        'children': json['children'] == null ? undefined : json['children'],
        'reference': ReferencePayloadFromJSON(json['reference']),
    };
}

export function ContentNodeToJSON(json: any): ContentNode {
    return ContentNodeToJSONTyped(json, false);
}

export function ContentNodeToJSONTyped(value?: ContentNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warnings': value['warnings'],
        'type': NodeTypeToJSON(value['type']),
        'block': BlockToJSON(value['block']),
        'children': value['children'],
        'reference': ReferencePayloadToJSON(value['reference']),
    };
}

