/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionSource } from './DefinitionSource';
import {
    DefinitionSourceFromJSON,
    DefinitionSourceFromJSONTyped,
    DefinitionSourceToJSON,
    DefinitionSourceToJSONTyped,
} from './DefinitionSource';
import type { DefinitionCategory } from './DefinitionCategory';
import {
    DefinitionCategoryFromJSON,
    DefinitionCategoryFromJSONTyped,
    DefinitionCategoryToJSON,
    DefinitionCategoryToJSONTyped,
} from './DefinitionCategory';

/**
 * 
 * @export
 * @interface CreateBusinessDefinitionRequest
 */
export interface CreateBusinessDefinitionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBusinessDefinitionRequest
     */
    term: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBusinessDefinitionRequest
     */
    definition: string;
    /**
     * 
     * @type {DefinitionCategory}
     * @memberof CreateBusinessDefinitionRequest
     */
    category: DefinitionCategory;
    /**
     * 
     * @type {DefinitionSource}
     * @memberof CreateBusinessDefinitionRequest
     */
    source: DefinitionSource;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateBusinessDefinitionRequest
     */
    entityTypeRefs: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateBusinessDefinitionRequest
     */
    attributeRefs: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateBusinessDefinitionRequest
     */
    isCustomized: boolean;
}



/**
 * Check if a given object implements the CreateBusinessDefinitionRequest interface.
 */
export function instanceOfCreateBusinessDefinitionRequest(value: object): value is CreateBusinessDefinitionRequest {
    if (!('term' in value) || value['term'] === undefined) return false;
    if (!('definition' in value) || value['definition'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('entityTypeRefs' in value) || value['entityTypeRefs'] === undefined) return false;
    if (!('attributeRefs' in value) || value['attributeRefs'] === undefined) return false;
    if (!('isCustomized' in value) || value['isCustomized'] === undefined) return false;
    return true;
}

export function CreateBusinessDefinitionRequestFromJSON(json: any): CreateBusinessDefinitionRequest {
    return CreateBusinessDefinitionRequestFromJSONTyped(json, false);
}

export function CreateBusinessDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBusinessDefinitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'term': json['term'],
        'definition': json['definition'],
        'category': DefinitionCategoryFromJSON(json['category']),
        'source': DefinitionSourceFromJSON(json['source']),
        'entityTypeRefs': json['entityTypeRefs'],
        'attributeRefs': json['attributeRefs'],
        'isCustomized': json['isCustomized'],
    };
}

export function CreateBusinessDefinitionRequestToJSON(json: any): CreateBusinessDefinitionRequest {
    return CreateBusinessDefinitionRequestToJSONTyped(json, false);
}

export function CreateBusinessDefinitionRequestToJSONTyped(value?: CreateBusinessDefinitionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'term': value['term'],
        'definition': value['definition'],
        'category': DefinitionCategoryToJSON(value['category']),
        'source': DefinitionSourceToJSON(value['source']),
        'entityTypeRefs': value['entityTypeRefs'],
        'attributeRefs': value['attributeRefs'],
        'isCustomized': value['isCustomized'],
    };
}

