/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CursorIndexWarning
 */
export interface CursorIndexWarning {
    /**
     * 
     * @type {string}
     * @memberof CursorIndexWarning
     */
    column: string;
    /**
     * 
     * @type {string}
     * @memberof CursorIndexWarning
     */
    suggestedDdl: string;
}

/**
 * Check if a given object implements the CursorIndexWarning interface.
 */
export function instanceOfCursorIndexWarning(value: object): value is CursorIndexWarning {
    if (!('column' in value) || value['column'] === undefined) return false;
    if (!('suggestedDdl' in value) || value['suggestedDdl'] === undefined) return false;
    return true;
}

export function CursorIndexWarningFromJSON(json: any): CursorIndexWarning {
    return CursorIndexWarningFromJSONTyped(json, false);
}

export function CursorIndexWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorIndexWarning {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'],
        'suggestedDdl': json['suggestedDdl'],
    };
}

export function CursorIndexWarningToJSON(json: any): CursorIndexWarning {
    return CursorIndexWarningToJSONTyped(json, false);
}

export function CursorIndexWarningToJSONTyped(value?: CursorIndexWarning | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': value['column'],
        'suggestedDdl': value['suggestedDdl'],
    };
}

