/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionStatus } from './ConnectionStatus';
import {
    ConnectionStatusFromJSON,
    ConnectionStatusFromJSONTyped,
    ConnectionStatusToJSON,
    ConnectionStatusToJSONTyped,
} from './ConnectionStatus';

/**
 * 
 * @export
 * @interface DataConnectorConnectionModel
 */
export interface DataConnectorConnectionModel {
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof DataConnectorConnectionModel
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    database: string;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof DataConnectorConnectionModel
     */
    sslMode: string;
    /**
     * 
     * @type {ConnectionStatus}
     * @memberof DataConnectorConnectionModel
     */
    connectionStatus: ConnectionStatus;
    /**
     * 
     * @type {Date}
     * @memberof DataConnectorConnectionModel
     */
    lastVerifiedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DataConnectorConnectionModel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DataConnectorConnectionModel
     */
    updatedAt?: Date | null;
}



/**
 * Check if a given object implements the DataConnectorConnectionModel interface.
 */
export function instanceOfDataConnectorConnectionModel(value: object): value is DataConnectorConnectionModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('sslMode' in value) || value['sslMode'] === undefined) return false;
    if (!('connectionStatus' in value) || value['connectionStatus'] === undefined) return false;
    return true;
}

export function DataConnectorConnectionModelFromJSON(json: any): DataConnectorConnectionModel {
    return DataConnectorConnectionModelFromJSONTyped(json, false);
}

export function DataConnectorConnectionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataConnectorConnectionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'name': json['name'],
        'host': json['host'],
        'port': json['port'],
        'database': json['database'],
        'user': json['user'],
        'sslMode': json['sslMode'],
        'connectionStatus': ConnectionStatusFromJSON(json['connectionStatus']),
        'lastVerifiedAt': json['lastVerifiedAt'] == null ? undefined : (new Date(json['lastVerifiedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function DataConnectorConnectionModelToJSON(json: any): DataConnectorConnectionModel {
    return DataConnectorConnectionModelToJSONTyped(json, false);
}

export function DataConnectorConnectionModelToJSONTyped(value?: DataConnectorConnectionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'name': value['name'],
        'host': value['host'],
        'port': value['port'],
        'database': value['database'],
        'user': value['user'],
        'sslMode': value['sslMode'],
        'connectionStatus': ConnectionStatusToJSON(value['connectionStatus']),
        'lastVerifiedAt': value['lastVerifiedAt'] == null ? value['lastVerifiedAt'] : value['lastVerifiedAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

