/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDefinitionImpact
 */
export interface DeleteDefinitionImpact {
    /**
     * 
     * @type {string}
     * @memberof DeleteDefinitionImpact
     */
    definitionId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteDefinitionImpact
     */
    definitionName: string;
    /**
     * 
     * @type {number}
     * @memberof DeleteDefinitionImpact
     */
    impactedLinkCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteDefinitionImpact
     */
    deletesDefinition: boolean;
}

/**
 * Check if a given object implements the DeleteDefinitionImpact interface.
 */
export function instanceOfDeleteDefinitionImpact(value: object): value is DeleteDefinitionImpact {
    if (!('definitionId' in value) || value['definitionId'] === undefined) return false;
    if (!('definitionName' in value) || value['definitionName'] === undefined) return false;
    if (!('impactedLinkCount' in value) || value['impactedLinkCount'] === undefined) return false;
    if (!('deletesDefinition' in value) || value['deletesDefinition'] === undefined) return false;
    return true;
}

export function DeleteDefinitionImpactFromJSON(json: any): DeleteDefinitionImpact {
    return DeleteDefinitionImpactFromJSONTyped(json, false);
}

export function DeleteDefinitionImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDefinitionImpact {
    if (json == null) {
        return json;
    }
    return {
        
        'definitionId': json['definitionId'],
        'definitionName': json['definitionName'],
        'impactedLinkCount': json['impactedLinkCount'],
        'deletesDefinition': json['deletesDefinition'],
    };
}

export function DeleteDefinitionImpactToJSON(json: any): DeleteDefinitionImpact {
    return DeleteDefinitionImpactToJSONTyped(json, false);
}

export function DeleteDefinitionImpactToJSONTyped(value?: DeleteDefinitionImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definitionId': value['definitionId'],
        'definitionName': value['definitionName'],
        'impactedLinkCount': value['impactedLinkCount'],
        'deletesDefinition': value['deletesDefinition'],
    };
}

