/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefaultValue } from './DefaultValue';
import {
    DefaultValueFromJSON,
    DefaultValueFromJSONTyped,
    DefaultValueToJSON,
    DefaultValueToJSONTyped,
} from './DefaultValue';
import type { DynamicDefaultFunction } from './DynamicDefaultFunction';
import {
    DynamicDefaultFunctionFromJSON,
    DynamicDefaultFunctionFromJSONTyped,
    DynamicDefaultFunctionToJSON,
    DynamicDefaultFunctionToJSONTyped,
} from './DynamicDefaultFunction';

/**
 * 
 * @export
 * @interface Dynamic
 */
export interface Dynamic extends DefaultValue {
    /**
     * 
     * @type {DynamicDefaultFunction}
     * @memberof Dynamic
     */
    _function?: DynamicDefaultFunction;
}



/**
 * Check if a given object implements the Dynamic interface.
 */
export function instanceOfDynamic(value: object): value is Dynamic {
    return true;
}

export function DynamicFromJSON(json: any): Dynamic {
    return DynamicFromJSONTyped(json, false);
}

export function DynamicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dynamic {
    if (json == null) {
        return json;
    }
    return {
        ...DefaultValueFromJSONTyped(json, true),
        '_function': json['function'] == null ? undefined : DynamicDefaultFunctionFromJSON(json['function']),
    };
}

export function DynamicToJSON(json: any): Dynamic {
    return DynamicToJSONTyped(json, false);
}

export function DynamicToJSONTyped(value?: Dynamic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...DefaultValueToJSONTyped(value, true),
        'function': DynamicDefaultFunctionToJSON(value['_function']),
    };
}

