/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnsureDemoReadyResult
 */
export interface EnsureDemoReadyResult {
    /**
     * 
     * @type {number}
     * @memberof EnsureDemoReadyResult
     */
    definitionsSeeded: number;
    /**
     * 
     * @type {number}
     * @memberof EnsureDemoReadyResult
     */
    definitionsSkipped: number;
}

/**
 * Check if a given object implements the EnsureDemoReadyResult interface.
 */
export function instanceOfEnsureDemoReadyResult(value: object): value is EnsureDemoReadyResult {
    if (!('definitionsSeeded' in value) || value['definitionsSeeded'] === undefined) return false;
    if (!('definitionsSkipped' in value) || value['definitionsSkipped'] === undefined) return false;
    return true;
}

export function EnsureDemoReadyResultFromJSON(json: any): EnsureDemoReadyResult {
    return EnsureDemoReadyResultFromJSONTyped(json, false);
}

export function EnsureDemoReadyResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnsureDemoReadyResult {
    if (json == null) {
        return json;
    }
    return {
        
        'definitionsSeeded': json['definitionsSeeded'],
        'definitionsSkipped': json['definitionsSkipped'],
    };
}

export function EnsureDemoReadyResultToJSON(json: any): EnsureDemoReadyResult {
    return EnsureDemoReadyResultToJSONTyped(json, false);
}

export function EnsureDemoReadyResultToJSONTyped(value?: EnsureDemoReadyResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definitionsSeeded': value['definitionsSeeded'],
        'definitionsSkipped': value['definitionsSkipped'],
    };
}

