/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAttributePayload } from './EntityAttributePayload';
import {
    EntityAttributePayloadFromJSON,
    EntityAttributePayloadFromJSONTyped,
    EntityAttributePayloadToJSON,
    EntityAttributePayloadToJSONTyped,
} from './EntityAttributePayload';

/**
 * 
 * @export
 * @interface EntityAttributeRequest
 */
export interface EntityAttributeRequest {
    /**
     * 
     * @type {EntityAttributePayload}
     * @memberof EntityAttributeRequest
     */
    payload: EntityAttributePayload;
}

/**
 * Check if a given object implements the EntityAttributeRequest interface.
 */
export function instanceOfEntityAttributeRequest(value: object): value is EntityAttributeRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function EntityAttributeRequestFromJSON(json: any): EntityAttributeRequest {
    return EntityAttributeRequestFromJSONTyped(json, false);
}

export function EntityAttributeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityAttributeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': EntityAttributePayloadFromJSON(json['payload']),
    };
}

export function EntityAttributeRequestToJSON(json: any): EntityAttributeRequest {
    return EntityAttributeRequestToJSONTyped(json, false);
}

export function EntityAttributeRequestToJSONTyped(value?: EntityAttributeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': EntityAttributePayloadToJSON(value['payload']),
    };
}

