/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityTypeSeedDetail
 */
export interface EntityTypeSeedDetail {
    /**
     * 
     * @type {string}
     * @memberof EntityTypeSeedDetail
     */
    entityTypeKey: string;
    /**
     * 
     * @type {string}
     * @memberof EntityTypeSeedDetail
     */
    entityTypeId: string;
    /**
     * 
     * @type {number}
     * @memberof EntityTypeSeedDetail
     */
    entitiesCreated: number;
    /**
     * 
     * @type {number}
     * @memberof EntityTypeSeedDetail
     */
    relationshipsCreated: number;
}

/**
 * Check if a given object implements the EntityTypeSeedDetail interface.
 */
export function instanceOfEntityTypeSeedDetail(value: object): value is EntityTypeSeedDetail {
    if (!('entityTypeKey' in value) || value['entityTypeKey'] === undefined) return false;
    if (!('entityTypeId' in value) || value['entityTypeId'] === undefined) return false;
    if (!('entitiesCreated' in value) || value['entitiesCreated'] === undefined) return false;
    if (!('relationshipsCreated' in value) || value['relationshipsCreated'] === undefined) return false;
    return true;
}

export function EntityTypeSeedDetailFromJSON(json: any): EntityTypeSeedDetail {
    return EntityTypeSeedDetailFromJSONTyped(json, false);
}

export function EntityTypeSeedDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityTypeSeedDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'entityTypeKey': json['entityTypeKey'],
        'entityTypeId': json['entityTypeId'],
        'entitiesCreated': json['entitiesCreated'],
        'relationshipsCreated': json['relationshipsCreated'],
    };
}

export function EntityTypeSeedDetailToJSON(json: any): EntityTypeSeedDetail {
    return EntityTypeSeedDetailToJSONTyped(json, false);
}

export function EntityTypeSeedDetailToJSONTyped(value?: EntityTypeSeedDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityTypeKey': value['entityTypeKey'],
        'entityTypeId': value['entityTypeId'],
        'entitiesCreated': value['entitiesCreated'],
        'relationshipsCreated': value['relationshipsCreated'],
    };
}

