/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaType } from './SchemaType';
import {
    SchemaTypeFromJSON,
    SchemaTypeFromJSONTyped,
    SchemaTypeToJSON,
    SchemaTypeToJSONTyped,
} from './SchemaType';

/**
 * 
 * @export
 * @interface ExistingMappingRef
 */
export interface ExistingMappingRef {
    /**
     * 
     * @type {string}
     * @memberof ExistingMappingRef
     */
    attributeName: string;
    /**
     * 
     * @type {SchemaType}
     * @memberof ExistingMappingRef
     */
    schemaType: SchemaType;
    /**
     * 
     * @type {boolean}
     * @memberof ExistingMappingRef
     */
    isIdentifier: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExistingMappingRef
     */
    isSyncCursor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExistingMappingRef
     */
    isMapped: boolean;
}



/**
 * Check if a given object implements the ExistingMappingRef interface.
 */
export function instanceOfExistingMappingRef(value: object): value is ExistingMappingRef {
    if (!('attributeName' in value) || value['attributeName'] === undefined) return false;
    if (!('schemaType' in value) || value['schemaType'] === undefined) return false;
    if (!('isIdentifier' in value) || value['isIdentifier'] === undefined) return false;
    if (!('isSyncCursor' in value) || value['isSyncCursor'] === undefined) return false;
    if (!('isMapped' in value) || value['isMapped'] === undefined) return false;
    return true;
}

export function ExistingMappingRefFromJSON(json: any): ExistingMappingRef {
    return ExistingMappingRefFromJSONTyped(json, false);
}

export function ExistingMappingRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExistingMappingRef {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeName': json['attributeName'],
        'schemaType': SchemaTypeFromJSON(json['schemaType']),
        'isIdentifier': json['isIdentifier'],
        'isSyncCursor': json['isSyncCursor'],
        'isMapped': json['isMapped'],
    };
}

export function ExistingMappingRefToJSON(json: any): ExistingMappingRef {
    return ExistingMappingRefToJSONTyped(json, false);
}

export function ExistingMappingRefToJSONTyped(value?: ExistingMappingRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributeName': value['attributeName'],
        'schemaType': SchemaTypeToJSON(value['schemaType']),
        'isIdentifier': value['isIdentifier'],
        'isSyncCursor': value['isSyncCursor'],
        'isMapped': value['isMapped'],
    };
}

