/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Role of an insights chat message author.
 * @export
 * @enum {string}
 */
export enum InsightsMessageRole {
    User = 'USER',
    Assistant = 'ASSISTANT'
}


export function instanceOfInsightsMessageRole(value: any): boolean {
    for (const key in InsightsMessageRole) {
        if (Object.prototype.hasOwnProperty.call(InsightsMessageRole, key)) {
            if (InsightsMessageRole[key as keyof typeof InsightsMessageRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InsightsMessageRoleFromJSON(json: any): InsightsMessageRole {
    return InsightsMessageRoleFromJSONTyped(json, false);
}

export function InsightsMessageRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightsMessageRole {
    return json as InsightsMessageRole;
}

export function InsightsMessageRoleToJSON(value?: InsightsMessageRole | null): any {
    return value as any;
}

export function InsightsMessageRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): InsightsMessageRole {
    return value as InsightsMessageRole;
}

