/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionStatus } from './ConnectionStatus';
import {
    ConnectionStatusFromJSON,
    ConnectionStatusFromJSONTyped,
    ConnectionStatusToJSON,
    ConnectionStatusToJSONTyped,
} from './ConnectionStatus';

/**
 * 
 * @export
 * @interface IntegrationConnectionModel
 */
export interface IntegrationConnectionModel {
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnectionModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnectionModel
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnectionModel
     */
    integrationId: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnectionModel
     */
    nangoConnectionId: string;
    /**
     * 
     * @type {ConnectionStatus}
     * @memberof IntegrationConnectionModel
     */
    status: ConnectionStatus;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof IntegrationConnectionModel
     */
    connectionMetadata?: { [key: string]: object; } | null;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationConnectionModel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof IntegrationConnectionModel
     */
    updatedAt?: Date | null;
}



/**
 * Check if a given object implements the IntegrationConnectionModel interface.
 */
export function instanceOfIntegrationConnectionModel(value: object): value is IntegrationConnectionModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('integrationId' in value) || value['integrationId'] === undefined) return false;
    if (!('nangoConnectionId' in value) || value['nangoConnectionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function IntegrationConnectionModelFromJSON(json: any): IntegrationConnectionModel {
    return IntegrationConnectionModelFromJSONTyped(json, false);
}

export function IntegrationConnectionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationConnectionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'integrationId': json['integrationId'],
        'nangoConnectionId': json['nangoConnectionId'],
        'status': ConnectionStatusFromJSON(json['status']),
        'connectionMetadata': json['connectionMetadata'] == null ? undefined : json['connectionMetadata'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function IntegrationConnectionModelToJSON(json: any): IntegrationConnectionModel {
    return IntegrationConnectionModelToJSONTyped(json, false);
}

export function IntegrationConnectionModelToJSONTyped(value?: IntegrationConnectionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'integrationId': value['integrationId'],
        'nangoConnectionId': value['nangoConnectionId'],
        'status': ConnectionStatusToJSON(value['status']),
        'connectionMetadata': value['connectionMetadata'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

