/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum IntegrationCategory {
    Crm = 'CRM',
    Payments = 'PAYMENTS',
    Support = 'SUPPORT',
    Email = 'EMAIL',
    ProjectManagement = 'PROJECT_MANAGEMENT',
    Communication = 'COMMUNICATION',
    Other = 'OTHER'
}


export function instanceOfIntegrationCategory(value: any): boolean {
    for (const key in IntegrationCategory) {
        if (Object.prototype.hasOwnProperty.call(IntegrationCategory, key)) {
            if (IntegrationCategory[key as keyof typeof IntegrationCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IntegrationCategoryFromJSON(json: any): IntegrationCategory {
    return IntegrationCategoryFromJSONTyped(json, false);
}

export function IntegrationCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationCategory {
    return json as IntegrationCategory;
}

export function IntegrationCategoryToJSON(value?: IntegrationCategory | null): any {
    return value as any;
}

export function IntegrationCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): IntegrationCategory {
    return value as IntegrationCategory;
}

