/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum LifecycleDomain {
    Acquisition = 'ACQUISITION',
    Marketing = 'MARKETING',
    Onboarding = 'ONBOARDING',
    Commerce = 'COMMERCE',
    Fulfillment = 'FULFILLMENT',
    Engagement = 'ENGAGEMENT',
    Support = 'SUPPORT',
    Billing = 'BILLING',
    Retention = 'RETENTION',
    Uncategorized = 'UNCATEGORIZED',
    Usage = 'USAGE'
}


export function instanceOfLifecycleDomain(value: any): boolean {
    for (const key in LifecycleDomain) {
        if (Object.prototype.hasOwnProperty.call(LifecycleDomain, key)) {
            if (LifecycleDomain[key as keyof typeof LifecycleDomain] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LifecycleDomainFromJSON(json: any): LifecycleDomain {
    return LifecycleDomainFromJSONTyped(json, false);
}

export function LifecycleDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): LifecycleDomain {
    return json as LifecycleDomain;
}

export function LifecycleDomainToJSON(value?: LifecycleDomain | null): any {
    return value as any;
}

export function LifecycleDomainToJSONTyped(value: any, ignoreDiscriminator: boolean): LifecycleDomain {
    return value as LifecycleDomain;
}

