/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MatchSignalType {
    Email = 'EMAIL',
    Phone = 'PHONE',
    Name = 'NAME',
    Company = 'COMPANY',
    CustomIdentifier = 'CUSTOM_IDENTIFIER'
}


export function instanceOfMatchSignalType(value: any): boolean {
    for (const key in MatchSignalType) {
        if (Object.prototype.hasOwnProperty.call(MatchSignalType, key)) {
            if (MatchSignalType[key as keyof typeof MatchSignalType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MatchSignalTypeFromJSON(json: any): MatchSignalType {
    return MatchSignalTypeFromJSONTyped(json, false);
}

export function MatchSignalTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchSignalType {
    return json as MatchSignalType;
}

export function MatchSignalTypeToJSON(value?: MatchSignalType | null): any {
    return value as any;
}

export function MatchSignalTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MatchSignalType {
    return value as MatchSignalType;
}

