/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlockContentMetadata } from './BlockContentMetadata';
import {
    instanceOfBlockContentMetadata,
    BlockContentMetadataFromJSON,
    BlockContentMetadataFromJSONTyped,
    BlockContentMetadataToJSON,
} from './BlockContentMetadata';
import type { BlockReferenceMetadata } from './BlockReferenceMetadata';
import {
    instanceOfBlockReferenceMetadata,
    BlockReferenceMetadataFromJSON,
    BlockReferenceMetadataFromJSONTyped,
    BlockReferenceMetadataToJSON,
} from './BlockReferenceMetadata';
import type { EntityReferenceMetadata } from './EntityReferenceMetadata';
import {
    instanceOfEntityReferenceMetadata,
    EntityReferenceMetadataFromJSON,
    EntityReferenceMetadataFromJSONTyped,
    EntityReferenceMetadataToJSON,
} from './EntityReferenceMetadata';

/**
 * @type Metadata
 * 
 * @export
 */
export type Metadata = BlockContentMetadata | BlockReferenceMetadata | EntityReferenceMetadata;

export function MetadataFromJSON(json: any): Metadata {
    return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfBlockContentMetadata(json)) {
        return BlockContentMetadataFromJSONTyped(json, true);
    }
    if (instanceOfBlockReferenceMetadata(json)) {
        return BlockReferenceMetadataFromJSONTyped(json, true);
    }
    if (instanceOfEntityReferenceMetadata(json)) {
        return EntityReferenceMetadataFromJSONTyped(json, true);
    }
    return {} as any;
}

export function MetadataToJSON(json: any): any {
    return MetadataToJSONTyped(json, false);
}

export function MetadataToJSONTyped(value?: Metadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfBlockContentMetadata(value)) {
        return BlockContentMetadataToJSON(value as BlockContentMetadata);
    }
    if (instanceOfBlockReferenceMetadata(value)) {
        return BlockReferenceMetadataToJSON(value as BlockReferenceMetadata);
    }
    if (instanceOfEntityReferenceMetadata(value)) {
        return EntityReferenceMetadataToJSON(value as EntityReferenceMetadata);
    }
    return {};
}

