/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteSourceType } from './NoteSourceType';
import {
    NoteSourceTypeFromJSON,
    NoteSourceTypeFromJSONTyped,
    NoteSourceTypeToJSON,
    NoteSourceTypeToJSONTyped,
} from './NoteSourceType';

/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Note
     */
    entityIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    title: string;
    /**
     * 
     * @type {Array<{ [key: string]: object; }>}
     * @memberof Note
     */
    content: Array<{ [key: string]: object; }>;
    /**
     * 
     * @type {NoteSourceType}
     * @memberof Note
     */
    sourceType: NoteSourceType;
    /**
     * 
     * @type {boolean}
     * @memberof Note
     */
    readonly: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    updatedBy?: string | null;
}



/**
 * Check if a given object implements the Note interface.
 */
export function instanceOfNote(value: object): value is Note {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('entityIds' in value) || value['entityIds'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('readonly' in value) || value['readonly'] === undefined) return false;
    return true;
}

export function NoteFromJSON(json: any): Note {
    return NoteFromJSONTyped(json, false);
}

export function NoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Note {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'entityIds': json['entityIds'],
        'workspaceId': json['workspaceId'],
        'title': json['title'],
        'content': json['content'],
        'sourceType': NoteSourceTypeFromJSON(json['sourceType']),
        'readonly': json['readonly'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
    };
}

export function NoteToJSON(json: any): Note {
    return NoteToJSONTyped(json, false);
}

export function NoteToJSONTyped(value?: Note | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'entityIds': value['entityIds'],
        'workspaceId': value['workspaceId'],
        'title': value['title'],
        'content': value['content'],
        'sourceType': NoteSourceTypeToJSON(value['sourceType']),
        'readonly': value['readonly'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
    };
}

