/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationInboxItem } from './NotificationInboxItem';
import {
    NotificationInboxItemFromJSON,
    NotificationInboxItemFromJSONTyped,
    NotificationInboxItemToJSON,
    NotificationInboxItemToJSONTyped,
} from './NotificationInboxItem';

/**
 * 
 * @export
 * @interface NotificationInboxResponse
 */
export interface NotificationInboxResponse {
    /**
     * 
     * @type {Array<NotificationInboxItem>}
     * @memberof NotificationInboxResponse
     */
    notifications: Array<NotificationInboxItem>;
    /**
     * 
     * @type {string}
     * @memberof NotificationInboxResponse
     */
    nextCursor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationInboxResponse
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the NotificationInboxResponse interface.
 */
export function instanceOfNotificationInboxResponse(value: object): value is NotificationInboxResponse {
    if (!('notifications' in value) || value['notifications'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function NotificationInboxResponseFromJSON(json: any): NotificationInboxResponse {
    return NotificationInboxResponseFromJSONTyped(json, false);
}

export function NotificationInboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationInboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': ((json['notifications'] as Array<any>).map(NotificationInboxItemFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'unreadCount': json['unreadCount'],
    };
}

export function NotificationInboxResponseToJSON(json: any): NotificationInboxResponse {
    return NotificationInboxResponseToJSONTyped(json, false);
}

export function NotificationInboxResponseToJSONTyped(value?: NotificationInboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notifications': ((value['notifications'] as Array<any>).map(NotificationInboxItemToJSON)),
        'nextCursor': value['nextCursor'],
        'unreadCount': value['unreadCount'],
    };
}

