/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Domain entity type that a notification references for navigation.
 * @export
 * @enum {string}
 */
export enum NotificationReferenceType {
    EntityResolution = 'ENTITY_RESOLUTION',
    WorkflowStep = 'WORKFLOW_STEP',
    WorkflowDefinition = 'WORKFLOW_DEFINITION',
    Entity = 'ENTITY',
    EntityType = 'ENTITY_TYPE',
    Workspace = 'WORKSPACE'
}


export function instanceOfNotificationReferenceType(value: any): boolean {
    for (const key in NotificationReferenceType) {
        if (Object.prototype.hasOwnProperty.call(NotificationReferenceType, key)) {
            if (NotificationReferenceType[key as keyof typeof NotificationReferenceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NotificationReferenceTypeFromJSON(json: any): NotificationReferenceType {
    return NotificationReferenceTypeFromJSONTyped(json, false);
}

export function NotificationReferenceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationReferenceType {
    return json as NotificationReferenceType;
}

export function NotificationReferenceTypeToJSON(value?: NotificationReferenceType | null): any {
    return value as any;
}

export function NotificationReferenceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NotificationReferenceType {
    return value as NotificationReferenceType;
}

