/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionCategory } from './DefinitionCategory';
import {
    DefinitionCategoryFromJSON,
    DefinitionCategoryFromJSONTyped,
    DefinitionCategoryToJSON,
    DefinitionCategoryToJSONTyped,
} from './DefinitionCategory';

/**
 * 
 * @export
 * @interface OnboardingBusinessDefinition
 */
export interface OnboardingBusinessDefinition {
    /**
     * 
     * @type {string}
     * @memberof OnboardingBusinessDefinition
     */
    term: string;
    /**
     * 
     * @type {string}
     * @memberof OnboardingBusinessDefinition
     */
    definition: string;
    /**
     * 
     * @type {DefinitionCategory}
     * @memberof OnboardingBusinessDefinition
     */
    category: DefinitionCategory;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingBusinessDefinition
     */
    isCustomized: boolean;
}



/**
 * Check if a given object implements the OnboardingBusinessDefinition interface.
 */
export function instanceOfOnboardingBusinessDefinition(value: object): value is OnboardingBusinessDefinition {
    if (!('term' in value) || value['term'] === undefined) return false;
    if (!('definition' in value) || value['definition'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('isCustomized' in value) || value['isCustomized'] === undefined) return false;
    return true;
}

export function OnboardingBusinessDefinitionFromJSON(json: any): OnboardingBusinessDefinition {
    return OnboardingBusinessDefinitionFromJSONTyped(json, false);
}

export function OnboardingBusinessDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingBusinessDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'term': json['term'],
        'definition': json['definition'],
        'category': DefinitionCategoryFromJSON(json['category']),
        'isCustomized': json['isCustomized'],
    };
}

export function OnboardingBusinessDefinitionToJSON(json: any): OnboardingBusinessDefinition {
    return OnboardingBusinessDefinitionToJSONTyped(json, false);
}

export function OnboardingBusinessDefinitionToJSONTyped(value?: OnboardingBusinessDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'term': value['term'],
        'definition': value['definition'],
        'category': DefinitionCategoryToJSON(value['category']),
        'isCustomized': value['isCustomized'],
    };
}

