/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OutputFieldType {
    Uuid = 'UUID',
    String = 'STRING',
    Boolean = 'BOOLEAN',
    Number = 'NUMBER',
    Map = 'MAP',
    List = 'LIST',
    Object = 'OBJECT',
    Entity = 'ENTITY',
    EntityList = 'ENTITY_LIST'
}


export function instanceOfOutputFieldType(value: any): boolean {
    for (const key in OutputFieldType) {
        if (Object.prototype.hasOwnProperty.call(OutputFieldType, key)) {
            if (OutputFieldType[key as keyof typeof OutputFieldType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputFieldTypeFromJSON(json: any): OutputFieldType {
    return OutputFieldTypeFromJSONTyped(json, false);
}

export function OutputFieldTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputFieldType {
    return json as OutputFieldType;
}

export function OutputFieldTypeToJSON(value?: OutputFieldType | null): any {
    return value as any;
}

export function OutputFieldTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputFieldType {
    return value as OutputFieldType;
}

