/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ReferenceType {
    Block = 'BLOCK',
    Entity = 'ENTITY'
}


export function instanceOfReferenceType(value: any): boolean {
    for (const key in ReferenceType) {
        if (Object.prototype.hasOwnProperty.call(ReferenceType, key)) {
            if (ReferenceType[key as keyof typeof ReferenceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReferenceTypeFromJSON(json: any): ReferenceType {
    return ReferenceTypeFromJSONTyped(json, false);
}

export function ReferenceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceType {
    return json as ReferenceType;
}

export function ReferenceTypeToJSON(value?: ReferenceType | null): any {
    return value as any;
}

export function ReferenceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferenceType {
    return value as ReferenceType;
}

