/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityRelationshipCardinality } from './EntityRelationshipCardinality';
import {
    EntityRelationshipCardinalityFromJSON,
    EntityRelationshipCardinalityFromJSONTyped,
    EntityRelationshipCardinalityToJSON,
    EntityRelationshipCardinalityToJSONTyped,
} from './EntityRelationshipCardinality';

/**
 * 
 * @export
 * @interface RelationshipTargetRule
 */
export interface RelationshipTargetRule {
    /**
     * 
     * @type {string}
     * @memberof RelationshipTargetRule
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipTargetRule
     */
    relationshipDefinitionId: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipTargetRule
     */
    targetEntityTypeId: string;
    /**
     * 
     * @type {EntityRelationshipCardinality}
     * @memberof RelationshipTargetRule
     */
    cardinalityOverride?: EntityRelationshipCardinality;
    /**
     * 
     * @type {string}
     * @memberof RelationshipTargetRule
     */
    inverseName: string;
    /**
     * 
     * @type {Date}
     * @memberof RelationshipTargetRule
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RelationshipTargetRule
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the RelationshipTargetRule interface.
 */
export function instanceOfRelationshipTargetRule(value: object): value is RelationshipTargetRule {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('relationshipDefinitionId' in value) || value['relationshipDefinitionId'] === undefined) return false;
    if (!('targetEntityTypeId' in value) || value['targetEntityTypeId'] === undefined) return false;
    if (!('inverseName' in value) || value['inverseName'] === undefined) return false;
    return true;
}

export function RelationshipTargetRuleFromJSON(json: any): RelationshipTargetRule {
    return RelationshipTargetRuleFromJSONTyped(json, false);
}

export function RelationshipTargetRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipTargetRule {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'relationshipDefinitionId': json['relationshipDefinitionId'],
        'targetEntityTypeId': json['targetEntityTypeId'],
        'cardinalityOverride': json['cardinalityOverride'] == null ? undefined : EntityRelationshipCardinalityFromJSON(json['cardinalityOverride']),
        'inverseName': json['inverseName'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function RelationshipTargetRuleToJSON(json: any): RelationshipTargetRule {
    return RelationshipTargetRuleToJSONTyped(json, false);
}

export function RelationshipTargetRuleToJSONTyped(value?: RelationshipTargetRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'relationshipDefinitionId': value['relationshipDefinitionId'],
        'targetEntityTypeId': value['targetEntityTypeId'],
        'cardinalityOverride': EntityRelationshipCardinalityToJSON(value['cardinalityOverride']),
        'inverseName': value['inverseName'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

