/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
    NodeToJSONTyped,
} from './Node';
import type { BlockOperationType } from './BlockOperationType';
import {
    BlockOperationTypeFromJSON,
    BlockOperationTypeFromJSONTyped,
    BlockOperationTypeToJSON,
    BlockOperationTypeToJSONTyped,
} from './BlockOperationType';

/**
 * 
 * @export
 * @interface RemoveBlockOperation
 */
export interface RemoveBlockOperation {
    /**
     * 
     * @type {string}
     * @memberof RemoveBlockOperation
     */
    blockId: string;
    /**
     * 
     * @type {BlockOperationType}
     * @memberof RemoveBlockOperation
     */
    type: BlockOperationType;
    /**
     * 
     * @type {Node}
     * @memberof RemoveBlockOperation
     */
    block: Node;
    /**
     * 
     * @type {string}
     * @memberof RemoveBlockOperation
     */
    parentId: string | null;
    /**
     * 
     * @type {number}
     * @memberof RemoveBlockOperation
     */
    index?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RemoveBlockOperation
     */
    childrenIds: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RemoveBlockOperation
     */
    fromParentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RemoveBlockOperation
     */
    toParentId?: string | null;
    /**
     * 
     * @type {Node}
     * @memberof RemoveBlockOperation
     */
    updatedContent: Node;
    /**
     * 
     * @type {number}
     * @memberof RemoveBlockOperation
     */
    fromIndex: number;
    /**
     * 
     * @type {number}
     * @memberof RemoveBlockOperation
     */
    toIndex: number;
}



/**
 * Check if a given object implements the RemoveBlockOperation interface.
 */
export function instanceOfRemoveBlockOperation(value: object): value is RemoveBlockOperation {
    if (!('blockId' in value) || value['blockId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('block' in value) || value['block'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('childrenIds' in value) || value['childrenIds'] === undefined) return false;
    if (!('updatedContent' in value) || value['updatedContent'] === undefined) return false;
    if (!('fromIndex' in value) || value['fromIndex'] === undefined) return false;
    if (!('toIndex' in value) || value['toIndex'] === undefined) return false;
    return true;
}

export function RemoveBlockOperationFromJSON(json: any): RemoveBlockOperation {
    return RemoveBlockOperationFromJSONTyped(json, false);
}

export function RemoveBlockOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveBlockOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'blockId': json['blockId'],
        'type': BlockOperationTypeFromJSON(json['type']),
        'block': NodeFromJSON(json['block']),
        'parentId': json['parentId'],
        'index': json['index'] == null ? undefined : json['index'],
        'childrenIds': json['childrenIds'],
        'fromParentId': json['fromParentId'] == null ? undefined : json['fromParentId'],
        'toParentId': json['toParentId'] == null ? undefined : json['toParentId'],
        'updatedContent': NodeFromJSON(json['updatedContent']),
        'fromIndex': json['fromIndex'],
        'toIndex': json['toIndex'],
    };
}

export function RemoveBlockOperationToJSON(json: any): RemoveBlockOperation {
    return RemoveBlockOperationToJSONTyped(json, false);
}

export function RemoveBlockOperationToJSONTyped(value?: RemoveBlockOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blockId': value['blockId'],
        'type': BlockOperationTypeToJSON(value['type']),
        'block': NodeToJSON(value['block']),
        'parentId': value['parentId'],
        'index': value['index'],
        'childrenIds': value['childrenIds'],
        'fromParentId': value['fromParentId'],
        'toParentId': value['toParentId'],
        'updatedContent': NodeToJSON(value['updatedContent']),
        'fromIndex': value['fromIndex'],
        'toIndex': value['toIndex'],
    };
}

