/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityRelationshipCardinality } from './EntityRelationshipCardinality';
import {
    EntityRelationshipCardinalityFromJSON,
    EntityRelationshipCardinalityFromJSONTyped,
    EntityRelationshipCardinalityToJSON,
    EntityRelationshipCardinalityToJSONTyped,
} from './EntityRelationshipCardinality';

/**
 * Request to save a target rule for a relationship definition
 * @export
 * @interface SaveTargetRuleRequest
 */
export interface SaveTargetRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveTargetRuleRequest
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveTargetRuleRequest
     */
    targetEntityTypeId: string;
    /**
     * 
     * @type {EntityRelationshipCardinality}
     * @memberof SaveTargetRuleRequest
     */
    cardinalityOverride?: EntityRelationshipCardinality | null;
    /**
     * 
     * @type {string}
     * @memberof SaveTargetRuleRequest
     */
    inverseName: string;
}



/**
 * Check if a given object implements the SaveTargetRuleRequest interface.
 */
export function instanceOfSaveTargetRuleRequest(value: object): value is SaveTargetRuleRequest {
    if (!('targetEntityTypeId' in value) || value['targetEntityTypeId'] === undefined) return false;
    if (!('inverseName' in value) || value['inverseName'] === undefined) return false;
    return true;
}

export function SaveTargetRuleRequestFromJSON(json: any): SaveTargetRuleRequest {
    return SaveTargetRuleRequestFromJSONTyped(json, false);
}

export function SaveTargetRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveTargetRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'targetEntityTypeId': json['targetEntityTypeId'],
        'cardinalityOverride': json['cardinalityOverride'] == null ? undefined : EntityRelationshipCardinalityFromJSON(json['cardinalityOverride']),
        'inverseName': json['inverseName'],
    };
}

export function SaveTargetRuleRequestToJSON(json: any): SaveTargetRuleRequest {
    return SaveTargetRuleRequestToJSONTyped(json, false);
}

export function SaveTargetRuleRequestToJSONTyped(value?: SaveTargetRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'targetEntityTypeId': value['targetEntityTypeId'],
        'cardinalityOverride': EntityRelationshipCardinalityToJSON(value['cardinalityOverride']),
        'inverseName': value['inverseName'],
    };
}

