/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SemanticAttributeClassification } from './SemanticAttributeClassification';
import {
    SemanticAttributeClassificationFromJSON,
    SemanticAttributeClassificationFromJSONTyped,
    SemanticAttributeClassificationToJSON,
    SemanticAttributeClassificationToJSONTyped,
} from './SemanticAttributeClassification';

/**
 * 
 * @export
 * @interface SaveSemanticMetadataRequest
 */
export interface SaveSemanticMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveSemanticMetadataRequest
     */
    definition?: string;
    /**
     * 
     * @type {SemanticAttributeClassification}
     * @memberof SaveSemanticMetadataRequest
     */
    classification?: SemanticAttributeClassification;
    /**
     * 
     * @type {Array<string>}
     * @memberof SaveSemanticMetadataRequest
     */
    tags: Array<string>;
}



/**
 * Check if a given object implements the SaveSemanticMetadataRequest interface.
 */
export function instanceOfSaveSemanticMetadataRequest(value: object): value is SaveSemanticMetadataRequest {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function SaveSemanticMetadataRequestFromJSON(json: any): SaveSemanticMetadataRequest {
    return SaveSemanticMetadataRequestFromJSONTyped(json, false);
}

export function SaveSemanticMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveSemanticMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'definition': json['definition'] == null ? undefined : json['definition'],
        'classification': json['classification'] == null ? undefined : SemanticAttributeClassificationFromJSON(json['classification']),
        'tags': json['tags'],
    };
}

export function SaveSemanticMetadataRequestToJSON(json: any): SaveSemanticMetadataRequest {
    return SaveSemanticMetadataRequestToJSONTyped(json, false);
}

export function SaveSemanticMetadataRequestToJSONTyped(value?: SaveSemanticMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definition': value['definition'],
        'classification': SemanticAttributeClassificationToJSON(value['classification']),
        'tags': value['tags'],
    };
}

