/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Dynamic } from './Dynamic';
import {
    instanceOfDynamic,
    DynamicFromJSON,
    DynamicFromJSONTyped,
    DynamicToJSON,
} from './Dynamic';
import type { Static } from './Static';
import {
    instanceOfStatic,
    StaticFromJSON,
    StaticFromJSONTyped,
    StaticToJSON,
} from './Static';

/**
 * @type SchemaOptionsDefaultValue
 * 
 * @export
 */
export type SchemaOptionsDefaultValue = Dynamic | Static;

export function SchemaOptionsDefaultValueFromJSON(json: any): SchemaOptionsDefaultValue {
    return SchemaOptionsDefaultValueFromJSONTyped(json, false);
}

export function SchemaOptionsDefaultValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaOptionsDefaultValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDynamic(json)) {
        return DynamicFromJSONTyped(json, true);
    }
    if (instanceOfStatic(json)) {
        return StaticFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SchemaOptionsDefaultValueToJSON(json: any): any {
    return SchemaOptionsDefaultValueToJSONTyped(json, false);
}

export function SchemaOptionsDefaultValueToJSONTyped(value?: SchemaOptionsDefaultValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDynamic(value)) {
        return DynamicToJSON(value as Dynamic);
    }
    if (instanceOfStatic(value)) {
        return StaticToJSON(value as Static);
    }
    return {};
}

