/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SortDir {
    Asc = 'ASC',
    Desc = 'DESC'
}


export function instanceOfSortDir(value: any): boolean {
    for (const key in SortDir) {
        if (Object.prototype.hasOwnProperty.call(SortDir, key)) {
            if (SortDir[key as keyof typeof SortDir] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortDirFromJSON(json: any): SortDir {
    return SortDirFromJSONTyped(json, false);
}

export function SortDirFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortDir {
    return json as SortDir;
}

export function SortDirToJSON(value?: SortDir | null): any {
    return value as any;
}

export function SortDirToJSONTyped(value: any, ignoreDiscriminator: boolean): SortDir {
    return value as SortDir;
}

