/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefaultValue } from './DefaultValue';
import {
    DefaultValueFromJSON,
    DefaultValueFromJSONTyped,
    DefaultValueToJSON,
    DefaultValueToJSONTyped,
} from './DefaultValue';

/**
 * 
 * @export
 * @interface Static
 */
export interface Static extends DefaultValue {
    /**
     * 
     * @type {object}
     * @memberof Static
     */
    value?: object;
}

/**
 * Check if a given object implements the Static interface.
 */
export function instanceOfStatic(value: object): value is Static {
    return true;
}

export function StaticFromJSON(json: any): Static {
    return StaticFromJSONTyped(json, false);
}

export function StaticFromJSONTyped(json: any, ignoreDiscriminator: boolean): Static {
    if (json == null) {
        return json;
    }
    return {
        ...DefaultValueFromJSONTyped(json, true),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function StaticToJSON(json: any): Static {
    return StaticToJSONTyped(json, false);
}

export function StaticToJSONTyped(value?: Static | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...DefaultValueToJSONTyped(value, true),
        'value': value['value'],
    };
}

