/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Category grouping for an insights demo suggested prompt.
 * @export
 * @enum {string}
 */
export enum SuggestedPromptCategory {
    Cohorts = 'COHORTS',
    Engagement = 'ENGAGEMENT',
    Retention = 'RETENTION',
    BusinessDefinitions = 'BUSINESS_DEFINITIONS',
    Comparison = 'COMPARISON',
    Overview = 'OVERVIEW'
}


export function instanceOfSuggestedPromptCategory(value: any): boolean {
    for (const key in SuggestedPromptCategory) {
        if (Object.prototype.hasOwnProperty.call(SuggestedPromptCategory, key)) {
            if (SuggestedPromptCategory[key as keyof typeof SuggestedPromptCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SuggestedPromptCategoryFromJSON(json: any): SuggestedPromptCategory {
    return SuggestedPromptCategoryFromJSONTyped(json, false);
}

export function SuggestedPromptCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedPromptCategory {
    return json as SuggestedPromptCategory;
}

export function SuggestedPromptCategoryToJSON(value?: SuggestedPromptCategory | null): any {
    return value as any;
}

export function SuggestedPromptCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): SuggestedPromptCategory {
    return value as SuggestedPromptCategory;
}

