/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuggestedPromptCategory } from './SuggestedPromptCategory';
import {
    SuggestedPromptCategoryFromJSON,
    SuggestedPromptCategoryFromJSONTyped,
    SuggestedPromptCategoryToJSON,
    SuggestedPromptCategoryToJSONTyped,
} from './SuggestedPromptCategory';
import type { RequiredDataSignal } from './RequiredDataSignal';
import {
    RequiredDataSignalFromJSON,
    RequiredDataSignalFromJSONTyped,
    RequiredDataSignalToJSON,
    RequiredDataSignalToJSONTyped,
} from './RequiredDataSignal';

/**
 * 
 * @export
 * @interface SuggestedPrompt
 */
export interface SuggestedPrompt {
    /**
     * 
     * @type {string}
     * @memberof SuggestedPrompt
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestedPrompt
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestedPrompt
     */
    prompt: string;
    /**
     * 
     * @type {SuggestedPromptCategory}
     * @memberof SuggestedPrompt
     */
    category: SuggestedPromptCategory;
    /**
     * 
     * @type {string}
     * @memberof SuggestedPrompt
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof SuggestedPrompt
     */
    score: number;
    /**
     * 
     * @type {Array<RequiredDataSignal>}
     * @memberof SuggestedPrompt
     */
    requiresData: Array<RequiredDataSignal>;
}



/**
 * Check if a given object implements the SuggestedPrompt interface.
 */
export function instanceOfSuggestedPrompt(value: object): value is SuggestedPrompt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('requiresData' in value) || value['requiresData'] === undefined) return false;
    return true;
}

export function SuggestedPromptFromJSON(json: any): SuggestedPrompt {
    return SuggestedPromptFromJSONTyped(json, false);
}

export function SuggestedPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedPrompt {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'prompt': json['prompt'],
        'category': SuggestedPromptCategoryFromJSON(json['category']),
        'description': json['description'],
        'score': json['score'],
        'requiresData': ((json['requiresData'] as Array<any>).map(RequiredDataSignalFromJSON)),
    };
}

export function SuggestedPromptToJSON(json: any): SuggestedPrompt {
    return SuggestedPromptToJSONTyped(json, false);
}

export function SuggestedPromptToJSONTyped(value?: SuggestedPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'prompt': value['prompt'],
        'category': SuggestedPromptCategoryToJSON(value['category']),
        'description': value['description'],
        'score': value['score'],
        'requiresData': ((value['requiresData'] as Array<any>).map(RequiredDataSignalToJSON)),
    };
}

