/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnConfiguration } from './ColumnConfiguration';
import {
    ColumnConfigurationFromJSON,
    ColumnConfigurationFromJSONTyped,
    ColumnConfigurationToJSON,
    ColumnConfigurationToJSONTyped,
} from './ColumnConfiguration';
import type { DisplayName } from './DisplayName';
import {
    DisplayNameFromJSON,
    DisplayNameFromJSONTyped,
    DisplayNameToJSON,
    DisplayNameToJSONTyped,
} from './DisplayName';
import type { SemanticGroup } from './SemanticGroup';
import {
    SemanticGroupFromJSON,
    SemanticGroupFromJSONTyped,
    SemanticGroupToJSON,
    SemanticGroupToJSONTyped,
} from './SemanticGroup';
import type { SaveSemanticMetadataRequest } from './SaveSemanticMetadataRequest';
import {
    SaveSemanticMetadataRequestFromJSON,
    SaveSemanticMetadataRequestFromJSONTyped,
    SaveSemanticMetadataRequestToJSON,
    SaveSemanticMetadataRequestToJSONTyped,
} from './SaveSemanticMetadataRequest';
import type { Icon } from './Icon';
import {
    IconFromJSON,
    IconFromJSONTyped,
    IconToJSON,
    IconToJSONTyped,
} from './Icon';
import type { LifecycleDomain } from './LifecycleDomain';
import {
    LifecycleDomainFromJSON,
    LifecycleDomainFromJSONTyped,
    LifecycleDomainToJSON,
    LifecycleDomainToJSONTyped,
} from './LifecycleDomain';

/**
 * 
 * @export
 * @interface UpdateEntityTypeConfigurationRequest
 */
export interface UpdateEntityTypeConfigurationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    id: string;
    /**
     * 
     * @type {DisplayName}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    name: DisplayName;
    /**
     * 
     * @type {Icon}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    icon: Icon;
    /**
     * 
     * @type {SemanticGroup}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    semanticGroup?: SemanticGroup;
    /**
     * 
     * @type {LifecycleDomain}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    lifecycleDomain?: LifecycleDomain;
    /**
     * 
     * @type {ColumnConfiguration}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    columnConfiguration?: ColumnConfiguration;
    /**
     * 
     * @type {SaveSemanticMetadataRequest}
     * @memberof UpdateEntityTypeConfigurationRequest
     */
    semantics?: SaveSemanticMetadataRequest;
}



/**
 * Check if a given object implements the UpdateEntityTypeConfigurationRequest interface.
 */
export function instanceOfUpdateEntityTypeConfigurationRequest(value: object): value is UpdateEntityTypeConfigurationRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function UpdateEntityTypeConfigurationRequestFromJSON(json: any): UpdateEntityTypeConfigurationRequest {
    return UpdateEntityTypeConfigurationRequestFromJSONTyped(json, false);
}

export function UpdateEntityTypeConfigurationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEntityTypeConfigurationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': DisplayNameFromJSON(json['name']),
        'icon': IconFromJSON(json['icon']),
        'semanticGroup': json['semanticGroup'] == null ? undefined : SemanticGroupFromJSON(json['semanticGroup']),
        'lifecycleDomain': json['lifecycleDomain'] == null ? undefined : LifecycleDomainFromJSON(json['lifecycleDomain']),
        'columnConfiguration': json['columnConfiguration'] == null ? undefined : ColumnConfigurationFromJSON(json['columnConfiguration']),
        'semantics': json['semantics'] == null ? undefined : SaveSemanticMetadataRequestFromJSON(json['semantics']),
    };
}

export function UpdateEntityTypeConfigurationRequestToJSON(json: any): UpdateEntityTypeConfigurationRequest {
    return UpdateEntityTypeConfigurationRequestToJSONTyped(json, false);
}

export function UpdateEntityTypeConfigurationRequestToJSONTyped(value?: UpdateEntityTypeConfigurationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': DisplayNameToJSON(value['name']),
        'icon': IconToJSON(value['icon']),
        'semanticGroup': SemanticGroupToJSON(value['semanticGroup']),
        'lifecycleDomain': LifecycleDomainToJSON(value['lifecycleDomain']),
        'columnConfiguration': ColumnConfigurationToJSON(value['columnConfiguration']),
        'semantics': SaveSemanticMetadataRequestToJSON(value['semantics']),
    };
}

