/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateNoteRequest
 */
export interface UpdateNoteRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateNoteRequest
     */
    title?: string;
    /**
     * 
     * @type {Array<{ [key: string]: object; }>}
     * @memberof UpdateNoteRequest
     */
    content?: Array<{ [key: string]: object; }>;
}

/**
 * Check if a given object implements the UpdateNoteRequest interface.
 */
export function instanceOfUpdateNoteRequest(value: object): value is UpdateNoteRequest {
    return true;
}

export function UpdateNoteRequestFromJSON(json: any): UpdateNoteRequest {
    return UpdateNoteRequestFromJSONTyped(json, false);
}

export function UpdateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function UpdateNoteRequestToJSON(json: any): UpdateNoteRequest {
    return UpdateNoteRequestToJSONTyped(json, false);
}

export function UpdateNoteRequestToJSONTyped(value?: UpdateNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

