/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileRequest
 */
export interface UploadFileRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UploadFileRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the UploadFileRequest interface.
 */
export function instanceOfUploadFileRequest(value: object): value is UploadFileRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function UploadFileRequestFromJSON(json: any): UploadFileRequest {
    return UploadFileRequestFromJSONTyped(json, false);
}

export function UploadFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function UploadFileRequestToJSON(json: any): UploadFileRequest {
    return UploadFileRequestToJSONTyped(json, false);
}

export function UploadFileRequestToJSONTyped(value?: UploadFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

