/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldFromJSONTyped,
    WorkflowNodeConfigFieldToJSON,
    WorkflowNodeConfigFieldToJSONTyped,
} from './WorkflowNodeConfigField';
import type { BulkUpdateErrorHandling } from './BulkUpdateErrorHandling';
import {
    BulkUpdateErrorHandlingFromJSON,
    BulkUpdateErrorHandlingFromJSONTyped,
    BulkUpdateErrorHandlingToJSON,
    BulkUpdateErrorHandlingToJSONTyped,
} from './BulkUpdateErrorHandling';
import type { QueryPagination } from './QueryPagination';
import {
    QueryPaginationFromJSON,
    QueryPaginationFromJSONTyped,
    QueryPaginationToJSON,
    QueryPaginationToJSONTyped,
} from './QueryPagination';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { EntityQuery } from './EntityQuery';
import {
    EntityQueryFromJSON,
    EntityQueryFromJSONTyped,
    EntityQueryToJSON,
    EntityQueryToJSONTyped,
} from './EntityQuery';
import type { WorkflowActionType } from './WorkflowActionType';
import {
    WorkflowActionTypeFromJSON,
    WorkflowActionTypeFromJSONTyped,
    WorkflowActionTypeToJSON,
    WorkflowActionTypeToJSONTyped,
} from './WorkflowActionType';

/**
 * Configuration for BULK_UPDATE_ENTITY action nodes that apply identical field updates to all entities matching a query.
 * @export
 * @interface WorkflowBulkUpdateEntityActionConfig
 */
export interface WorkflowBulkUpdateEntityActionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    version?: number;
    /**
     * 
     * @type {EntityQuery}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    query?: EntityQuery;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    payload?: { [key: string]: string; };
    /**
     * 
     * @type {BulkUpdateErrorHandling}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    errorHandling?: BulkUpdateErrorHandling;
    /**
     * 
     * @type {QueryPagination}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    pagination?: QueryPagination;
    /**
     * 
     * @type {number}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    configSchema?: Array<WorkflowNodeConfigField>;
    /**
     * 
     * @type {WorkflowActionType}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    subType?: WorkflowActionType;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    config?: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowBulkUpdateEntityActionConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowBulkUpdateEntityActionConfig interface.
 */
export function instanceOfWorkflowBulkUpdateEntityActionConfig(value: object): value is WorkflowBulkUpdateEntityActionConfig {
    return true;
}

export function WorkflowBulkUpdateEntityActionConfigFromJSON(json: any): WorkflowBulkUpdateEntityActionConfig {
    return WorkflowBulkUpdateEntityActionConfigFromJSONTyped(json, false);
}

export function WorkflowBulkUpdateEntityActionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowBulkUpdateEntityActionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'query': json['query'] == null ? undefined : EntityQueryFromJSON(json['query']),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'errorHandling': json['errorHandling'] == null ? undefined : BulkUpdateErrorHandlingFromJSON(json['errorHandling']),
        'pagination': json['pagination'] == null ? undefined : QueryPaginationFromJSON(json['pagination']),
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'configSchema': json['configSchema'] == null ? undefined : ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
        'subType': json['subType'] == null ? undefined : WorkflowActionTypeFromJSON(json['subType']),
        'config': json['config'] == null ? undefined : json['config'],
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowBulkUpdateEntityActionConfigToJSON(json: any): WorkflowBulkUpdateEntityActionConfig {
    return WorkflowBulkUpdateEntityActionConfigToJSONTyped(json, false);
}

export function WorkflowBulkUpdateEntityActionConfigToJSONTyped(value?: WorkflowBulkUpdateEntityActionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'query': EntityQueryToJSON(value['query']),
        'payload': value['payload'],
        'errorHandling': BulkUpdateErrorHandlingToJSON(value['errorHandling']),
        'pagination': QueryPaginationToJSON(value['pagination']),
        'timeoutSeconds': value['timeoutSeconds'],
        'configSchema': value['configSchema'] == null ? undefined : ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
        'subType': WorkflowActionTypeToJSON(value['subType']),
        'config': value['config'],
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

