/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceRoles } from './WorkspaceRoles';
import {
    WorkspaceRolesFromJSON,
    WorkspaceRolesFromJSONTyped,
    WorkspaceRolesToJSON,
    WorkspaceRolesToJSONTyped,
} from './WorkspaceRoles';
import type { UserDisplay } from './UserDisplay';
import {
    UserDisplayFromJSON,
    UserDisplayFromJSONTyped,
    UserDisplayToJSON,
    UserDisplayToJSONTyped,
} from './UserDisplay';
import type { WorkspaceDisplay } from './WorkspaceDisplay';
import {
    WorkspaceDisplayFromJSON,
    WorkspaceDisplayFromJSONTyped,
    WorkspaceDisplayToJSON,
    WorkspaceDisplayToJSONTyped,
} from './WorkspaceDisplay';

/**
 * 
 * @export
 * @interface WorkspaceMember
 */
export interface WorkspaceMember {
    /**
     * 
     * @type {WorkspaceDisplay}
     * @memberof WorkspaceMember
     */
    workspace: WorkspaceDisplay;
    /**
     * 
     * @type {UserDisplay}
     * @memberof WorkspaceMember
     */
    user: UserDisplay;
    /**
     * 
     * @type {WorkspaceRoles}
     * @memberof WorkspaceMember
     */
    role: WorkspaceRoles;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceMember
     */
    memberSince: Date;
}



/**
 * Check if a given object implements the WorkspaceMember interface.
 */
export function instanceOfWorkspaceMember(value: object): value is WorkspaceMember {
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('memberSince' in value) || value['memberSince'] === undefined) return false;
    return true;
}

export function WorkspaceMemberFromJSON(json: any): WorkspaceMember {
    return WorkspaceMemberFromJSONTyped(json, false);
}

export function WorkspaceMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceMember {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace': WorkspaceDisplayFromJSON(json['workspace']),
        'user': UserDisplayFromJSON(json['user']),
        'role': WorkspaceRolesFromJSON(json['role']),
        'memberSince': (new Date(json['memberSince'])),
    };
}

export function WorkspaceMemberToJSON(json: any): WorkspaceMember {
    return WorkspaceMemberToJSONTyped(json, false);
}

export function WorkspaceMemberToJSONTyped(value?: WorkspaceMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspace': WorkspaceDisplayToJSON(value['workspace']),
        'user': UserDisplayToJSON(value['user']),
        'role': WorkspaceRolesToJSON(value['role']),
        'memberSince': value['memberSince'].toISOString(),
    };
}

