/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeOutputField } from './WorkflowNodeOutputField';
import {
    WorkflowNodeOutputFieldFromJSON,
    WorkflowNodeOutputFieldFromJSONTyped,
    WorkflowNodeOutputFieldToJSON,
    WorkflowNodeOutputFieldToJSONTyped,
} from './WorkflowNodeOutputField';

/**
 * 
 * @export
 * @interface WorkflowNodeOutputMetadata
 */
export interface WorkflowNodeOutputMetadata {
    /**
     * 
     * @type {Array<WorkflowNodeOutputField>}
     * @memberof WorkflowNodeOutputMetadata
     */
    fields: Array<WorkflowNodeOutputField>;
}

/**
 * Check if a given object implements the WorkflowNodeOutputMetadata interface.
 */
export function instanceOfWorkflowNodeOutputMetadata(value: object): value is WorkflowNodeOutputMetadata {
    if (!('fields' in value) || value['fields'] === undefined) return false;
    return true;
}

export function WorkflowNodeOutputMetadataFromJSON(json: any): WorkflowNodeOutputMetadata {
    return WorkflowNodeOutputMetadataFromJSONTyped(json, false);
}

export function WorkflowNodeOutputMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowNodeOutputMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'fields': ((json['fields'] as Array<any>).map(WorkflowNodeOutputFieldFromJSON)),
    };
}

export function WorkflowNodeOutputMetadataToJSON(json: any): WorkflowNodeOutputMetadata {
    return WorkflowNodeOutputMetadataToJSONTyped(json, false);
}

export function WorkflowNodeOutputMetadataToJSONTyped(value?: WorkflowNodeOutputMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fields': ((value['fields'] as Array<any>).map(WorkflowNodeOutputFieldToJSON)),
    };
}

