/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNode } from './WorkflowNode';
import {
    WorkflowNodeFromJSON,
    WorkflowNodeFromJSONTyped,
    WorkflowNodeToJSON,
    WorkflowNodeToJSONTyped,
} from './WorkflowNode';
import type { WorkflowStatus } from './WorkflowStatus';
import {
    WorkflowStatusFromJSON,
    WorkflowStatusFromJSONTyped,
    WorkflowStatusToJSON,
    WorkflowStatusToJSONTyped,
} from './WorkflowStatus';

/**
 * 
 * @export
 * @interface WorkflowExecutionNodeRecord
 */
export interface WorkflowExecutionNodeRecord {
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecutionNodeRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecutionNodeRecord
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecutionNodeRecord
     */
    executionId: string;
    /**
     * 
     * @type {WorkflowNode}
     * @memberof WorkflowExecutionNodeRecord
     */
    node?: WorkflowNode;
    /**
     * 
     * @type {number}
     * @memberof WorkflowExecutionNodeRecord
     */
    sequenceIndex: number;
    /**
     * 
     * @type {WorkflowStatus}
     * @memberof WorkflowExecutionNodeRecord
     */
    status: WorkflowStatus;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowExecutionNodeRecord
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowExecutionNodeRecord
     */
    completedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecutionNodeRecord
     */
    duration?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowExecutionNodeRecord
     */
    attempt: number;
    /**
     * 
     * @type {object}
     * @memberof WorkflowExecutionNodeRecord
     */
    input?: object;
    /**
     * 
     * @type {object}
     * @memberof WorkflowExecutionNodeRecord
     */
    output?: object;
    /**
     * 
     * @type {object}
     * @memberof WorkflowExecutionNodeRecord
     */
    error?: object;
}



/**
 * Check if a given object implements the WorkflowExecutionNodeRecord interface.
 */
export function instanceOfWorkflowExecutionNodeRecord(value: object): value is WorkflowExecutionNodeRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('sequenceIndex' in value) || value['sequenceIndex'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    return true;
}

export function WorkflowExecutionNodeRecordFromJSON(json: any): WorkflowExecutionNodeRecord {
    return WorkflowExecutionNodeRecordFromJSONTyped(json, false);
}

export function WorkflowExecutionNodeRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowExecutionNodeRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'executionId': json['executionId'],
        'node': json['node'] == null ? undefined : WorkflowNodeFromJSON(json['node']),
        'sequenceIndex': json['sequenceIndex'],
        'status': WorkflowStatusFromJSON(json['status']),
        'startedAt': (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'duration': json['duration'] == null ? undefined : json['duration'],
        'attempt': json['attempt'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function WorkflowExecutionNodeRecordToJSON(json: any): WorkflowExecutionNodeRecord {
    return WorkflowExecutionNodeRecordToJSONTyped(json, false);
}

export function WorkflowExecutionNodeRecordToJSONTyped(value?: WorkflowExecutionNodeRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'executionId': value['executionId'],
        'node': WorkflowNodeToJSON(value['node']),
        'sequenceIndex': value['sequenceIndex'],
        'status': WorkflowStatusToJSON(value['status']),
        'startedAt': value['startedAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'duration': value['duration'],
        'attempt': value['attempt'],
        'input': value['input'],
        'output': value['output'],
        'error': value['error'],
    };
}

