/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceDefaultCurrency
 */
export interface WorkspaceDefaultCurrency {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDefaultCurrency
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDefaultCurrency
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDefaultCurrency
     */
    symbol?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceDefaultCurrency
     */
    defaultFractionDigits?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceDefaultCurrency
     */
    numericCode?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDefaultCurrency
     */
    numericCodeAsString?: string;
}

/**
 * Check if a given object implements the WorkspaceDefaultCurrency interface.
 */
export function instanceOfWorkspaceDefaultCurrency(value: object): value is WorkspaceDefaultCurrency {
    return true;
}

export function WorkspaceDefaultCurrencyFromJSON(json: any): WorkspaceDefaultCurrency {
    return WorkspaceDefaultCurrencyFromJSONTyped(json, false);
}

export function WorkspaceDefaultCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceDefaultCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'defaultFractionDigits': json['defaultFractionDigits'] == null ? undefined : json['defaultFractionDigits'],
        'numericCode': json['numericCode'] == null ? undefined : json['numericCode'],
        'numericCodeAsString': json['numericCodeAsString'] == null ? undefined : json['numericCodeAsString'],
    };
}

export function WorkspaceDefaultCurrencyToJSON(json: any): WorkspaceDefaultCurrency {
    return WorkspaceDefaultCurrencyToJSONTyped(json, false);
}

export function WorkspaceDefaultCurrencyToJSONTyped(value?: WorkspaceDefaultCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currencyCode': value['currencyCode'],
        'displayName': value['displayName'],
        'symbol': value['symbol'],
        'defaultFractionDigits': value['defaultFractionDigits'],
        'numericCode': value['numericCode'],
        'numericCodeAsString': value['numericCodeAsString'],
    };
}

