/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldFromJSONTyped,
    WorkflowNodeConfigFieldToJSON,
    WorkflowNodeConfigFieldToJSONTyped,
} from './WorkflowNodeConfigField';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';

/**
 * Configuration for FUNCTION category nodes.
 * @export
 * @interface WorkflowFunctionConfig
 */
export interface WorkflowFunctionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowFunctionConfig
     */
    version?: number;
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowFunctionConfig
     */
    configSchema?: Array<WorkflowNodeConfigField>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowFunctionConfig
     */
    config?: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowFunctionConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowFunctionConfig interface.
 */
export function instanceOfWorkflowFunctionConfig(value: object): value is WorkflowFunctionConfig {
    return true;
}

export function WorkflowFunctionConfigFromJSON(json: any): WorkflowFunctionConfig {
    return WorkflowFunctionConfigFromJSONTyped(json, false);
}

export function WorkflowFunctionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowFunctionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'configSchema': json['configSchema'] == null ? undefined : ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
        'config': json['config'] == null ? undefined : json['config'],
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowFunctionConfigToJSON(json: any): WorkflowFunctionConfig {
    return WorkflowFunctionConfigToJSONTyped(json, false);
}

export function WorkflowFunctionConfigToJSONTyped(value?: WorkflowFunctionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'configSchema': value['configSchema'] == null ? undefined : ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
        'config': value['config'],
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

