/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldFromJSONTyped,
    WorkflowNodeConfigFieldToJSON,
    WorkflowNodeConfigFieldToJSONTyped,
} from './WorkflowNodeConfigField';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowControlType } from './WorkflowControlType';
import {
    WorkflowControlTypeFromJSON,
    WorkflowControlTypeFromJSONTyped,
    WorkflowControlTypeToJSON,
    WorkflowControlTypeToJSONTyped,
} from './WorkflowControlType';

/**
 * Configuration for CONDITION control flow nodes.
 * @export
 * @interface WorkflowConditionControlConfig
 */
export interface WorkflowConditionControlConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowConditionControlConfig
     */
    version: number;
    /**
     * SQL-like expression to evaluate. Must return boolean.
     * @type {string}
     * @memberof WorkflowConditionControlConfig
     */
    expression: string;
    /**
     * Optional entity ID to use as evaluation context. Can be a static UUID or template.
     * @type {string}
     * @memberof WorkflowConditionControlConfig
     */
    contextEntityId?: string | null;
    /**
     * Optional timeout override in seconds
     * @type {number}
     * @memberof WorkflowConditionControlConfig
     */
    timeoutSeconds?: number | null;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowConditionControlConfig
     */
    type: WorkflowNodeType;
    /**
     * 
     * @type {WorkflowControlType}
     * @memberof WorkflowConditionControlConfig
     */
    subType: WorkflowControlType;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowConditionControlConfig
     */
    config: { [key: string]: object; };
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowConditionControlConfig
     */
    configSchema: Array<WorkflowNodeConfigField>;
}



/**
 * Check if a given object implements the WorkflowConditionControlConfig interface.
 */
export function instanceOfWorkflowConditionControlConfig(value: object): value is WorkflowConditionControlConfig {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('expression' in value) || value['expression'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subType' in value) || value['subType'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('configSchema' in value) || value['configSchema'] === undefined) return false;
    return true;
}

export function WorkflowConditionControlConfigFromJSON(json: any): WorkflowConditionControlConfig {
    return WorkflowConditionControlConfigFromJSONTyped(json, false);
}

export function WorkflowConditionControlConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowConditionControlConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'expression': json['expression'],
        'contextEntityId': json['contextEntityId'] == null ? undefined : json['contextEntityId'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'type': WorkflowNodeTypeFromJSON(json['type']),
        'subType': WorkflowControlTypeFromJSON(json['subType']),
        'config': json['config'],
        'configSchema': ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
    };
}

export function WorkflowConditionControlConfigToJSON(json: any): WorkflowConditionControlConfig {
    return WorkflowConditionControlConfigToJSONTyped(json, false);
}

export function WorkflowConditionControlConfigToJSONTyped(value?: WorkflowConditionControlConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'expression': value['expression'],
        'contextEntityId': value['contextEntityId'],
        'timeoutSeconds': value['timeoutSeconds'],
        'type': WorkflowNodeTypeToJSON(value['type']),
        'subType': WorkflowControlTypeToJSON(value['subType']),
        'config': value['config'],
        'configSchema': ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
    };
}

