/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldFromJSONTyped,
    WorkflowNodeConfigFieldToJSON,
    WorkflowNodeConfigFieldToJSONTyped,
} from './WorkflowNodeConfigField';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowTriggerType } from './WorkflowTriggerType';
import {
    WorkflowTriggerTypeFromJSON,
    WorkflowTriggerTypeFromJSONTyped,
    WorkflowTriggerTypeToJSON,
    WorkflowTriggerTypeToJSONTyped,
} from './WorkflowTriggerType';
import type { OperationType } from './OperationType';
import {
    OperationTypeFromJSON,
    OperationTypeFromJSONTyped,
    OperationTypeToJSON,
    OperationTypeToJSONTyped,
} from './OperationType';

/**
 * Configuration for ENTITY_EVENT trigger nodes. Triggers workflow execution when entity operations occur.
 * @export
 * @interface WorkflowEntityEventTriggerConfig
 */
export interface WorkflowEntityEventTriggerConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    key: string;
    /**
     * 
     * @type {OperationType}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    operation: OperationType;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    field: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    expressions: object;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    config: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    type?: WorkflowNodeType;
    /**
     * 
     * @type {WorkflowTriggerType}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    subType: WorkflowTriggerType;
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowEntityEventTriggerConfig
     */
    configSchema: Array<WorkflowNodeConfigField>;
}



/**
 * Check if a given object implements the WorkflowEntityEventTriggerConfig interface.
 */
export function instanceOfWorkflowEntityEventTriggerConfig(value: object): value is WorkflowEntityEventTriggerConfig {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('expressions' in value) || value['expressions'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('subType' in value) || value['subType'] === undefined) return false;
    if (!('configSchema' in value) || value['configSchema'] === undefined) return false;
    return true;
}

export function WorkflowEntityEventTriggerConfigFromJSON(json: any): WorkflowEntityEventTriggerConfig {
    return WorkflowEntityEventTriggerConfigFromJSONTyped(json, false);
}

export function WorkflowEntityEventTriggerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowEntityEventTriggerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'key': json['key'],
        'operation': OperationTypeFromJSON(json['operation']),
        'field': json['field'],
        'expressions': json['expressions'],
        'config': json['config'],
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
        'subType': WorkflowTriggerTypeFromJSON(json['subType']),
        'configSchema': ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
    };
}

export function WorkflowEntityEventTriggerConfigToJSON(json: any): WorkflowEntityEventTriggerConfig {
    return WorkflowEntityEventTriggerConfigToJSONTyped(json, false);
}

export function WorkflowEntityEventTriggerConfigToJSONTyped(value?: WorkflowEntityEventTriggerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'key': value['key'],
        'operation': OperationTypeToJSON(value['operation']),
        'field': value['field'],
        'expressions': value['expressions'],
        'config': value['config'],
        'type': WorkflowNodeTypeToJSON(value['type']),
        'subType': WorkflowTriggerTypeToJSON(value['subType']),
        'configSchema': ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
    };
}

