/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldFromJSONTyped,
    WorkflowNodeConfigFieldToJSON,
    WorkflowNodeConfigFieldToJSONTyped,
} from './WorkflowNodeConfigField';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeFromJSONTyped,
    WorkflowNodeTypeToJSON,
    WorkflowNodeTypeToJSONTyped,
} from './WorkflowNodeType';
import type { WorkflowActionType } from './WorkflowActionType';
import {
    WorkflowActionTypeFromJSON,
    WorkflowActionTypeFromJSONTyped,
    WorkflowActionTypeToJSON,
    WorkflowActionTypeToJSONTyped,
} from './WorkflowActionType';

/**
 * Configuration for DELETE_ENTITY action nodes.
 * @export
 * @interface WorkflowDeleteEntityActionConfig
 */
export interface WorkflowDeleteEntityActionConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    version: number;
    /**
     * UUID of the entity to delete. Can be a static UUID or template.
     * @type {string}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    entityId: string;
    /**
     * Optional timeout override in seconds
     * @type {number}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    timeoutSeconds?: number | null;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    type: WorkflowNodeType;
    /**
     * 
     * @type {WorkflowActionType}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    subType: WorkflowActionType;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    config: { [key: string]: object; };
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowDeleteEntityActionConfig
     */
    configSchema: Array<WorkflowNodeConfigField>;
}



/**
 * Check if a given object implements the WorkflowDeleteEntityActionConfig interface.
 */
export function instanceOfWorkflowDeleteEntityActionConfig(value: object): value is WorkflowDeleteEntityActionConfig {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subType' in value) || value['subType'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('configSchema' in value) || value['configSchema'] === undefined) return false;
    return true;
}

export function WorkflowDeleteEntityActionConfigFromJSON(json: any): WorkflowDeleteEntityActionConfig {
    return WorkflowDeleteEntityActionConfigFromJSONTyped(json, false);
}

export function WorkflowDeleteEntityActionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDeleteEntityActionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'entityId': json['entityId'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'type': WorkflowNodeTypeFromJSON(json['type']),
        'subType': WorkflowActionTypeFromJSON(json['subType']),
        'config': json['config'],
        'configSchema': ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
    };
}

export function WorkflowDeleteEntityActionConfigToJSON(json: any): WorkflowDeleteEntityActionConfig {
    return WorkflowDeleteEntityActionConfigToJSONTyped(json, false);
}

export function WorkflowDeleteEntityActionConfigToJSONTyped(value?: WorkflowDeleteEntityActionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'entityId': value['entityId'],
        'timeoutSeconds': value['timeoutSeconds'],
        'type': WorkflowNodeTypeToJSON(value['type']),
        'subType': WorkflowActionTypeToJSON(value['subType']),
        'config': value['config'],
        'configSchema': ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
    };
}

