/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplicationEntityType,
  BlockEnvironment,
  BlockHydrationResult,
  BlockType,
  CreateBlockTypeRequest,
  HydrateBlocksRequest,
  OverwriteEnvironmentRequest,
  OverwriteEnvironmentResponse,
  SaveEnvironmentRequest,
  SaveEnvironmentResponse,
} from '../models/index';
import {
    ApplicationEntityTypeFromJSON,
    ApplicationEntityTypeToJSON,
    BlockEnvironmentFromJSON,
    BlockEnvironmentToJSON,
    BlockHydrationResultFromJSON,
    BlockHydrationResultToJSON,
    BlockTypeFromJSON,
    BlockTypeToJSON,
    CreateBlockTypeRequestFromJSON,
    CreateBlockTypeRequestToJSON,
    HydrateBlocksRequestFromJSON,
    HydrateBlocksRequestToJSON,
    OverwriteEnvironmentRequestFromJSON,
    OverwriteEnvironmentRequestToJSON,
    OverwriteEnvironmentResponseFromJSON,
    OverwriteEnvironmentResponseToJSON,
    SaveEnvironmentRequestFromJSON,
    SaveEnvironmentRequestToJSON,
    SaveEnvironmentResponseFromJSON,
    SaveEnvironmentResponseToJSON,
} from '../models/index';

export interface GetBlockEnvironmentRequest {
    workspaceId: string;
    type: ApplicationEntityType;
    entityId: string;
}

export interface GetBlockTypeByKeyRequest {
    key: string;
}

export interface GetBlockTypesRequest {
    workspaceId: string;
}

export interface HydrateBlocksOperationRequest {
    hydrateBlocksRequest: HydrateBlocksRequest;
}

export interface OverwriteBlockEnvironmentRequest {
    overwriteEnvironmentRequest: OverwriteEnvironmentRequest;
}

export interface PublishBlockTypeRequest {
    createBlockTypeRequest: CreateBlockTypeRequest;
}

export interface SaveBlockEnvironmentRequest {
    saveEnvironmentRequest: SaveEnvironmentRequest;
}

export interface UpdateBlockTypeRequest {
    blockTypeId: string;
    blockType: BlockType;
}

/**
 * 
 */
export class BlockApi extends runtime.BaseAPI {

    /**
     * Retrieves the block environment for the specified entity. Creates a default layout if none exists (lazy initialization).
     * Get Block Environment
     */
    async getBlockEnvironmentRaw(requestParameters: GetBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockEnvironment>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getBlockEnvironment().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getBlockEnvironment().'
            );
        }

        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling getBlockEnvironment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/environment/workspace/{workspaceId}/type/{type}/id/{entityId}`;
        urlPath = urlPath.replace(`{${"workspaceId"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"entityId"}}`, encodeURIComponent(String(requestParameters['entityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockEnvironmentFromJSON(jsonValue));
    }

    /**
     * Retrieves the block environment for the specified entity. Creates a default layout if none exists (lazy initialization).
     * Get Block Environment
     */
    async getBlockEnvironment(requestParameters: GetBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockEnvironment> {
        const response = await this.getBlockEnvironmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a block type by its unique key.
     * Get block type by key
     */
    async getBlockTypeByKeyRaw(requestParameters: GetBlockTypeByKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockType>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling getBlockTypeByKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/schema/key/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockTypeFromJSON(jsonValue));
    }

    /**
     * Retrieves a block type by its unique key.
     * Get block type by key
     */
    async getBlockTypeByKey(requestParameters: GetBlockTypeByKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockType> {
        const response = await this.getBlockTypeByKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all block types associated with a specific workspace.
     * Get block types for workspace
     */
    async getBlockTypesRaw(requestParameters: GetBlockTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BlockType>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getBlockTypes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/schema/workspace/{workspaceId}`;
        urlPath = urlPath.replace(`{${"workspaceId"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BlockTypeFromJSON));
    }

    /**
     * Retrieves all block types associated with a specific workspace.
     * Get block types for workspace
     */
    async getBlockTypes(requestParameters: GetBlockTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BlockType>> {
        const response = await this.getBlockTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolves entity references for one or more blocks in a single batched request. This is used for progressive loading of entity data without fetching everything upfront. Only blocks with entity reference metadata will be hydrated; other blocks are skipped.
     * Hydrate Blocks
     */
    async hydrateBlocksRaw(requestParameters: HydrateBlocksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: BlockHydrationResult; }>> {
        if (requestParameters['hydrateBlocksRequest'] == null) {
            throw new runtime.RequiredError(
                'hydrateBlocksRequest',
                'Required parameter "hydrateBlocksRequest" was null or undefined when calling hydrateBlocks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/environment/hydrate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HydrateBlocksRequestToJSON(requestParameters['hydrateBlocksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, BlockHydrationResultFromJSON));
    }

    /**
     * Resolves entity references for one or more blocks in a single batched request. This is used for progressive loading of entity data without fetching everything upfront. Only blocks with entity reference metadata will be hydrated; other blocks are skipped.
     * Hydrate Blocks
     */
    async hydrateBlocks(requestParameters: HydrateBlocksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: BlockHydrationResult; }> {
        const response = await this.hydrateBlocksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Overwrites the entire block environment with the provided data.
     * Overwrite Block Environment
     */
    async overwriteBlockEnvironmentRaw(requestParameters: OverwriteBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverwriteEnvironmentResponse>> {
        if (requestParameters['overwriteEnvironmentRequest'] == null) {
            throw new runtime.RequiredError(
                'overwriteEnvironmentRequest',
                'Required parameter "overwriteEnvironmentRequest" was null or undefined when calling overwriteBlockEnvironment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/environment/overwrite`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OverwriteEnvironmentRequestToJSON(requestParameters['overwriteEnvironmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverwriteEnvironmentResponseFromJSON(jsonValue));
    }

    /**
     * Overwrites the entire block environment with the provided data.
     * Overwrite Block Environment
     */
    async overwriteBlockEnvironment(requestParameters: OverwriteBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverwriteEnvironmentResponse> {
        const response = await this.overwriteBlockEnvironmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates and publishes a new block type based on the provided request data.
     * Create a new block type
     */
    async publishBlockTypeRaw(requestParameters: PublishBlockTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockType>> {
        if (requestParameters['createBlockTypeRequest'] == null) {
            throw new runtime.RequiredError(
                'createBlockTypeRequest',
                'Required parameter "createBlockTypeRequest" was null or undefined when calling publishBlockType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/schema/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBlockTypeRequestToJSON(requestParameters['createBlockTypeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockTypeFromJSON(jsonValue));
    }

    /**
     * Creates and publishes a new block type based on the provided request data.
     * Create a new block type
     */
    async publishBlockType(requestParameters: PublishBlockTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockType> {
        const response = await this.publishBlockTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Saves the block environment including layout and structural operations.
     * Save Block Environment
     */
    async saveBlockEnvironmentRaw(requestParameters: SaveBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveEnvironmentResponse>> {
        if (requestParameters['saveEnvironmentRequest'] == null) {
            throw new runtime.RequiredError(
                'saveEnvironmentRequest',
                'Required parameter "saveEnvironmentRequest" was null or undefined when calling saveBlockEnvironment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/environment/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveEnvironmentRequestToJSON(requestParameters['saveEnvironmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveEnvironmentResponseFromJSON(jsonValue));
    }

    /**
     * Saves the block environment including layout and structural operations.
     * Save Block Environment
     */
    async saveBlockEnvironment(requestParameters: SaveBlockEnvironmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveEnvironmentResponse> {
        const response = await this.saveBlockEnvironmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a block type with the specified ID. Does not allow changing the scope of the block type.
     * Update an existing block type
     */
    async updateBlockTypeRaw(requestParameters: UpdateBlockTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['blockTypeId'] == null) {
            throw new runtime.RequiredError(
                'blockTypeId',
                'Required parameter "blockTypeId" was null or undefined when calling updateBlockType().'
            );
        }

        if (requestParameters['blockType'] == null) {
            throw new runtime.RequiredError(
                'blockType',
                'Required parameter "blockType" was null or undefined when calling updateBlockType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/block/schema/{blockTypeId}`;
        urlPath = urlPath.replace(`{${"blockTypeId"}}`, encodeURIComponent(String(requestParameters['blockTypeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BlockTypeToJSON(requestParameters['blockType']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a block type with the specified ID. Does not allow changing the scope of the block type.
     * Update an existing block type
     */
    async updateBlockType(requestParameters: UpdateBlockTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateBlockTypeRaw(requestParameters, initOverrides);
    }

}
