/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's profile
         * @description Retrieves the profile of the authenticated user based on the current session.
         */
        get: operations["getCurrentUser"];
        /**
         * Update current user's profile
         * @description Updates the profile of the authenticated user based on the provided data.
         */
        put: operations["updateUserProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}/member/role/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMemberRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateOrganisation"];
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/{blockTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an existing block type
         * @description Updates a block type with the specified ID. Does not allow changing the scope of the block type.
         */
        put: operations["updateBlockType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/{blockTypeId}/archive/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Archive a block type
         * @description Archives a block type by its ID. The block type will still be visible to users currently using it but cannot be used in new blocks.
         */
        put: operations["updateArchiveStatusByBlockTypeId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/reject/{inviteToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}/email/{email}/role/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteToOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/accept/{inviteToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entity/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new entity type
         * @description Creates and publishes a new entity type for the specified organisation.
         */
        post: operations["createEntityType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new block type
         * @description Creates and publishes a new block type based on the provided request data.
         */
        post: operations["publishBlockType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/overwrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Overwrite Block Environment
         * @description Overwrites the entire block environment with the provided data.
         */
        post: operations["overwriteBlockEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/hydrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hydrate Blocks
         * @description Resolves entity references for one or more blocks in a single batched request. This is used for progressive loading of entity data without fetching everything upfront. Only blocks with entity reference metadata will be hydrated; other blocks are skipped.
         */
        post: operations["hydrateBlocks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Block Environment
         * @description Saves the block environment including layout and structural operations.
         */
        post: operations["saveBlockEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user by ID
         * @description Retrieves a specific user's profile by their ID, if the user has access.
         */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /**
         * Delete a user profile by ID
         * @description Deletes a user profile with the specified ID, if the user has access.
         */
        delete: operations["deleteUserProfileById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganisation"];
        put?: never;
        post?: never;
        delete: operations["deleteOrganisation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganisationInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entity/schema/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all entity types for an organisation
         * @description Retrieves all entity types associated with the specified organisation.
         */
        get: operations["getEntityTypesForOrganisation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entity/schema/organisation/{organisationId}/key/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an entity type by key for an organisation
         * @description Retrieves a specific entity type by its key associated with the specified organisation.
         */
        get: operations["getEntityTypeByKeyForOrganisation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/organisation/{organisationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block types for organisation
         * @description Retrieves all block types associated with a specific organisation.
         */
        get: operations["getBlockTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/schema/key/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block type by key
         * @description Retrieves a block type by its unique key.
         */
        get: operations["getBlockTypeByKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/block/environment/organisation/{organisationId}/type/{type}/id/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block Environment
         * @description Retrieves the block environment for the specified entity. Creates a default layout if none exists (lazy initialization).
         */
        get: operations["getBlockEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/{organisationId}/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMemberFromOrganisation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation/invite/organisation/{organisationId}/invitation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            street: string;
            city: string;
            state: string;
            postalCode: string;
            country: string;
        };
        MembershipDetails: {
            organisation?: components["schemas"]["Organisation"];
            role: components["schemas"]["OrganisationRoles"];
            /** Format: date-time */
            memberSince: string;
        };
        Organisation: {
            /** Format: uuid */
            id: string;
            name: string;
            plan: components["schemas"]["OrganisationPlan"];
            defaultCurrency: {
                currencyCode?: string;
                /** Format: int32 */
                numericCode?: number;
                numericCodeAsString?: string;
                displayName?: string;
                symbol?: string;
                /** Format: int32 */
                defaultFractionDigits?: number;
            };
            avatarUrl?: string;
            businessNumber?: string;
            taxId?: string;
            address?: components["schemas"]["Address"];
            organisationPaymentDetails?: components["schemas"]["OrganisationPaymentDetails"];
            /** Format: int32 */
            memberCount: number;
            /** Format: date-time */
            createdAt?: string;
            members: components["schemas"]["OrganisationMember"][];
            invites: components["schemas"]["OrganisationInvite"][];
        };
        OrganisationInvite: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            email: string;
            inviteToken: string;
            /** Format: uuid */
            invitedBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            role: components["schemas"]["OrganisationRoles"];
            status: components["schemas"]["OrganisationInviteStatus"];
        };
        /** @enum {string} */
        OrganisationInviteStatus: OrganisationInviteStatus;
        OrganisationMember: {
            user: components["schemas"]["UserDisplay"];
            membershipDetails: components["schemas"]["MembershipDetails"];
        };
        OrganisationPaymentDetails: {
            bsb?: string;
            accountNumber?: string;
            accountName?: string;
        };
        /** @enum {string} */
        OrganisationPlan: OrganisationPlan;
        /** @enum {string} */
        OrganisationRoles: OrganisationRoles;
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            phone?: string;
            avatarUrl?: string;
            memberships: components["schemas"]["MembershipDetails"][];
            defaultOrganisation?: components["schemas"]["Organisation"];
        };
        UserDisplay: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            avatarUrl?: string;
        };
        BindingSource: {
            type: string;
        };
        BlockBinding: {
            prop: string;
            source: components["schemas"]["Computed"] | components["schemas"]["DataPath"];
        };
        BlockComponentNode: {
            id: string;
            type: components["schemas"]["ComponentType"];
            props: {
                [key: string]: unknown;
            };
            bindings: components["schemas"]["BlockBinding"][];
            slots?: {
                [key: string]: string[];
            };
            slotLayout?: {
                [key: string]: components["schemas"]["LayoutGrid"];
            };
            widgetMeta?: {
                [key: string]: Record<string, never>;
            };
            visible?: components["schemas"]["Condition"];
            fetchPolicy: components["schemas"]["BlockFetchPolicy"];
        };
        BlockDisplay: {
            form: components["schemas"]["FormStructure"];
            render: components["schemas"]["BlockRenderStructure"];
        };
        /** @enum {string} */
        BlockFetchPolicy: BlockFetchPolicy;
        /** @enum {string} */
        BlockFormWidgetType: BlockFormWidgetType;
        BlockRenderStructure: {
            /** Format: int32 */
            version: number;
            layoutGrid: components["schemas"]["LayoutGrid"];
            components: {
                [key: string]: components["schemas"]["BlockComponentNode"];
            };
            theme?: components["schemas"]["ThemeTokens"];
        };
        BlockType: {
            /** Format: uuid */
            id: string;
            key: string;
            /** Format: int32 */
            version: number;
            name: string;
            /** Format: uuid */
            sourceId?: string;
            nesting?: components["schemas"]["BlockTypeNesting"];
            description?: string;
            /** Format: uuid */
            organisationId?: string;
            archived: boolean;
            strictness: components["schemas"]["ValidationScope"];
            system: boolean;
            schema: components["schemas"]["Schema"];
            display: components["schemas"]["BlockDisplay"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        BlockTypeNesting: {
            /** Format: int32 */
            max?: number;
            allowedTypes: string[];
        };
        /** @enum {string} */
        ComponentType: ComponentType;
        Computed: {
            type: "Computed";
        } & (Omit<components["schemas"]["BindingSource"], "type"> & {
            expr: string;
            engine: string;
        });
        Condition: {
            op: components["schemas"]["Op"];
            left: components["schemas"]["Path"] | components["schemas"]["Value"];
            right?: components["schemas"]["Path"] | components["schemas"]["Value"];
        };
        /** @enum {string} */
        DataFormat: DataFormat;
        DataPath: {
            type: "DataPath";
        } & (Omit<components["schemas"]["BindingSource"], "type"> & {
            path: string;
        });
        /** @enum {string} */
        DataType: DataType;
        FormStructure: {
            fields: {
                [key: string]: components["schemas"]["FormWidgetConfig"];
            };
        };
        FormWidgetConfig: {
            type: components["schemas"]["BlockFormWidgetType"];
            label: string;
            description?: string;
            tooltip?: string;
            placeholder?: string;
            options?: components["schemas"]["Option"][];
        };
        GridRect: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            margin?: number;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            locked: boolean;
        };
        LayoutGrid: {
            layout: components["schemas"]["GridRect"];
            items: components["schemas"]["LayoutGridItem"][];
        };
        LayoutGridItem: {
            id: string;
            rect: components["schemas"]["GridRect"];
        };
        /** @enum {string} */
        Op: Op;
        Operand: {
            kind: string;
        };
        Option: {
            label: string;
            value: string;
        };
        /** @enum {string} */
        OptionSortingType: OptionSortingType;
        Path: {
            kind: "Path";
        } & (Omit<components["schemas"]["Operand"], "kind"> & {
            path: string;
        });
        Schema: {
            name: string;
            description?: string;
            type: components["schemas"]["DataType"];
            format?: components["schemas"]["DataFormat"];
            required: boolean;
            properties?: {
                [key: string]: components["schemas"]["Schema"];
            };
            items?: components["schemas"]["Schema"];
            unique: boolean;
            protected: boolean;
            options?: components["schemas"]["SchemaOptions"];
        };
        SchemaOptions: {
            default?: Record<string, never>;
            regex?: string;
            enum?: (string | number | boolean)[];
            enumSorting?: components["schemas"]["OptionSortingType"];
            /** Format: int32 */
            minLength?: number;
            /** Format: int32 */
            maxLength?: number;
            /** Format: double */
            minimum?: number;
            /** Format: double */
            maximum?: number;
        };
        ThemeTokens: {
            variant?: string;
            colorRole?: string;
            tone?: string;
        };
        /** @enum {string} */
        ValidationScope: ValidationScope;
        Value: {
            kind: "Value";
        } & (Omit<components["schemas"]["Operand"], "kind"> & {
            value?: Record<string, never>;
        });
        OrganisationCreationRequest: {
            name: string;
            avatarUrl?: string;
            plan: components["schemas"]["OrganisationPlan"];
            defaultCurrency: string;
            isDefault: boolean;
            businessNumber?: string;
            taxId?: string;
            address: components["schemas"]["Address"];
            payment?: components["schemas"]["OrganisationPaymentDetails"];
            customAttributes: {
                [key: string]: Record<string, never>;
            };
        };
        CreateEntityTypeRequest: {
            name: components["schemas"]["DisplayName"];
            key: string;
            /** Format: uuid */
            organisationId: string;
            identifier: string;
            description?: string;
            type: components["schemas"]["EntityCategory"];
            schema: components["schemas"]["Schema"];
            relationships?: components["schemas"]["EntityRelationshipDefinition"][];
            order?: string[];
        };
        DisplayName: {
            singular: string;
            plural: string;
        };
        /** @enum {string} */
        EntityCategory: EntityCategory;
        /** @enum {string} */
        EntityRelationshipCardinality: EntityRelationshipCardinality;
        EntityRelationshipDefinition: {
            name: string;
            key: string;
            cardinality: components["schemas"]["EntityRelationshipCardinality"];
            /** Format: int32 */
            minOccurs?: number;
            /** Format: int32 */
            maxOccurs?: number;
            entityTypeKeys?: string[];
            allowPolymorphic: boolean;
            bidirectional: boolean;
            inverseName?: string;
            required: boolean;
        };
        EntityType: {
            /** Format: uuid */
            id: string;
            key: string;
            /** Format: int32 */
            version: number;
            name: components["schemas"]["DisplayName"];
            protected: boolean;
            identifierKey: string;
            description?: string;
            /** Format: uuid */
            organisationId?: string;
            type: components["schemas"]["EntityCategory"];
            schema: components["schemas"]["Schema"];
            relationships?: components["schemas"]["EntityRelationshipDefinition"][];
            order: string[];
            /** Format: int64 */
            entitiesCount: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
            attributes: components["schemas"]["PairIntegerInteger"];
        };
        PairIntegerInteger: {
            /** Format: int32 */
            first: number;
            /** Format: int32 */
            second: number;
        };
        CreateBlockTypeRequest: {
            key: string;
            name: string;
            description?: string;
            mode: components["schemas"]["ValidationScope"];
            schema: components["schemas"]["Schema"];
            display: components["schemas"]["BlockDisplay"];
            /** Format: uuid */
            organisationId: string;
        };
        Block: {
            /** Format: uuid */
            id: string;
            name?: string;
            /** Format: uuid */
            organisationId: string;
            type: components["schemas"]["BlockType"];
            payload: components["schemas"]["EntityReferenceMetadata"] | components["schemas"]["BlockReferenceMetadata"] | components["schemas"]["BlockContentMetadata"];
            archived: boolean;
            validationErrors?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        BlockContentMetadata: WithRequired<components["schemas"]["Metadata"], "deletable" | "meta" | "readonly" | "type"> & {
            data: {
                [key: string]: unknown;
            };
            listConfig?: components["schemas"]["BlockListConfiguration"];
        };
        BlockEnvironment: {
            layout: components["schemas"]["BlockTreeLayout"];
            trees: components["schemas"]["BlockTree"][];
        };
        BlockListConfiguration: {
            listType?: string[];
            allowDuplicates: boolean;
            display: components["schemas"]["ListDisplayConfig"];
            config: components["schemas"]["ListConfig"];
        };
        /** @enum {string} */
        BlockListOrderingMode: BlockListOrderingMode;
        BlockMeta: {
            validationErrors: string[];
            computedFields?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            lastValidatedVersion?: number;
        };
        /** @enum {string} */
        BlockMetadataType: BlockMetadataType;
        /** @enum {string} */
        BlockReferenceFetchPolicy: BlockReferenceFetchPolicy;
        BlockReferenceMetadata: components["schemas"]["ReferenceMetadata"] & {
            /** Format: int32 */
            expandDepth: number;
            item: components["schemas"]["ReferenceItem"];
        };
        /** @enum {string} */
        BlockReferenceWarning: BlockReferenceWarning;
        BlockTree: {
            root: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
        };
        BlockTreeLayout: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            layout: components["schemas"]["TreeLayout"];
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        /** @description Reference to another block tree */
        BlockTreeReference: WithRequired<components["schemas"]["ReferencePayload"], "type"> & {
            reference?: components["schemas"]["ReferenceItemBlockTree"];
        };
        BreakpointConfig: {
            /** Format: int32 */
            w: number;
            /** Format: int32 */
            c: number;
        };
        ColumnOptions: {
            breakpoints?: components["schemas"]["BreakpointConfig"][];
            layout?: string;
            breakpointForWindow?: string;
            /** Format: int32 */
            columnMax?: number;
            /** Format: int32 */
            columnWidth?: number;
        };
        /** @description Content node containing a block with optional children */
        ContentNode: WithRequired<components["schemas"]["Node"], "block" | "type" | "warnings"> & {
            children?: components["schemas"]["Node"][];
        };
        DraggableOptions: {
            cancel?: string;
            /** Format: int32 */
            pause?: number;
            handle?: string;
            appendTo?: string;
            scroll?: boolean;
        };
        Entity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organisationId: string;
            entityType: components["schemas"]["EntityType"];
            /** Format: int32 */
            typeVersion: number;
            name?: string;
            payload: {
                [key: string]: Record<string, never>;
            };
            validationErrors?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            updatedBy?: string;
        };
        /** @description Reference to one or more of an organisation's entities (e.g. teams, projects, clients) */
        EntityReference: WithRequired<components["schemas"]["ReferencePayload"], "type"> & {
            reference?: components["schemas"]["ReferenceItemEntity"][];
        };
        EntityReferenceMetadata: components["schemas"]["ReferenceMetadata"] & {
            presentation: components["schemas"]["Presentation"];
            items: components["schemas"]["ReferenceItem"][];
            projection: components["schemas"]["Projection"];
            listType?: components["schemas"]["Entity"];
            display: components["schemas"]["ListDisplayConfig"];
            config: components["schemas"]["ListConfig"];
            allowDuplicates: boolean;
        };
        FilterSpec: {
            expr: {
                [key: string]: unknown;
            };
        };
        ListConfig: {
            mode: components["schemas"]["BlockListOrderingMode"];
            sort?: components["schemas"]["SortSpec"];
            filters: components["schemas"]["FilterSpec"][];
            filterLogic: components["schemas"]["ListFilterLogicType"];
        };
        ListDisplayConfig: {
            /** Format: int32 */
            itemSpacing: number;
            showDragHandles: boolean;
            emptyMessage: string;
            paging?: components["schemas"]["PagingSpec"];
        };
        /** @enum {string} */
        ListFilterLogicType: ListFilterLogicType;
        Metadata: {
            type: components["schemas"]["BlockMetadataType"];
            meta: components["schemas"]["BlockMeta"];
            readonly: boolean;
            deletable: boolean;
        };
        Node: {
            warnings: string[];
            type: components["schemas"]["NodeType"];
            block: components["schemas"]["Block"];
        };
        /** @enum {string} */
        NodeType: NodeType;
        OverwriteEnvironmentRequest: {
            /** Format: uuid */
            layoutId: string;
            /** Format: uuid */
            organisationId: string;
            /** Format: int32 */
            version: number;
            environment: components["schemas"]["BlockEnvironment"];
        };
        PagingSpec: {
            /** Format: int32 */
            pageSize: number;
        };
        /** @enum {string} */
        Presentation: Presentation;
        Projection: {
            fields: string[];
            /** Format: uuid */
            templateId?: string;
        };
        ReferenceItem: {
            /** Format: uuid */
            id: string;
            labelOverride?: string;
            badge?: string;
        };
        ReferenceItemBlockTree: {
            /** Format: uuid */
            id: string;
            path?: string;
            /** Format: int32 */
            orderIndex?: number;
            entity?: components["schemas"]["BlockTree"];
            warning?: components["schemas"]["BlockReferenceWarning"];
        };
        ReferenceItemEntity: {
            /** Format: uuid */
            id: string;
            path?: string;
            /** Format: int32 */
            orderIndex?: number;
            entity?: components["schemas"]["Entity"];
            warning?: components["schemas"]["BlockReferenceWarning"];
        };
        ReferenceMetadata: WithRequired<components["schemas"]["Metadata"], "deletable" | "meta" | "readonly" | "type"> & {
            path: string;
            fetchPolicy: components["schemas"]["BlockReferenceFetchPolicy"];
        };
        /** @description Reference node containing a block with entity or block tree references */
        ReferenceNode: WithRequired<components["schemas"]["Node"], "block" | "type" | "warnings"> & {
            reference: components["schemas"]["EntityReference"] | components["schemas"]["BlockTreeReference"];
        } & {
            reference: components["schemas"]["ReferencePayload"];
        };
        ReferencePayload: {
            type: components["schemas"]["ReferenceType"];
        };
        /** @enum {string} */
        ReferenceType: ReferenceType;
        RenderContent: {
            id: string;
            key: string;
            renderType: components["schemas"]["RenderType"];
            blockType: components["schemas"]["NodeType"];
        };
        /** @enum {string} */
        RenderType: RenderType;
        ResizableOptions: {
            handles?: string;
            autoHide?: boolean;
        };
        /** @enum {string} */
        SortDir: SortDir;
        SortSpec: {
            by: string;
            dir: components["schemas"]["SortDir"];
        };
        TreeLayout: {
            acceptWidgets?: boolean;
            alwaysShowResizeHandle?: boolean;
            animate?: boolean;
            auto?: boolean;
            /** Format: int32 */
            cellHeight?: number;
            resizable?: components["schemas"]["ResizableOptions"];
            draggable?: components["schemas"]["DraggableOptions"];
            /** Format: int32 */
            margin?: number;
            /** Format: int32 */
            marginTop?: number;
            /** Format: int32 */
            marginRight?: number;
            /** Format: int32 */
            marginBottom?: number;
            /** Format: int32 */
            marginLeft?: number;
            /** @description Number of columns or the string 'auto' */
            column?: number | string;
            columnOpts?: components["schemas"]["ColumnOptions"];
            disableDrag?: boolean;
            disableOneColumnMode?: boolean;
            disableResize?: boolean;
            float?: boolean;
            handle?: string;
            handleClass?: string;
            itemClass?: string;
            /** Format: int32 */
            maxRow?: number;
            /** Format: int32 */
            minRow?: number;
            /** Format: int32 */
            oneColumnSize?: number;
            placeholderClass?: string;
            placeholderText?: string;
            removable?: boolean;
            /** Format: int32 */
            removeTimeout?: number;
            /** Format: int32 */
            row?: number;
            rtl?: boolean;
            staticGrid?: boolean;
            styleInHead?: boolean;
            sizeToContent?: boolean;
            layout?: string;
            class?: string;
            children?: components["schemas"]["Widget"][];
        };
        Widget: {
            id: string;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            w: number;
            /** Format: int32 */
            h?: number;
            /** Format: int32 */
            minW?: number;
            /** Format: int32 */
            minH?: number;
            /** Format: int32 */
            maxW?: number;
            /** Format: int32 */
            maxH?: number;
            autoPosition?: boolean;
            locked?: boolean;
            noResize?: boolean;
            noMove?: boolean;
            content?: components["schemas"]["RenderContent"];
            subGridOpts?: components["schemas"]["TreeLayout"];
        };
        OverwriteEnvironmentResponse: {
            success: boolean;
            environment: components["schemas"]["BlockEnvironment"];
        };
        EntityReferenceRequest: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ReferenceType"];
            /** Format: int32 */
            index?: number;
        };
        HydrateBlocksRequest: {
            references: {
                [key: string]: components["schemas"]["EntityReferenceRequest"][];
            };
            /** Format: uuid */
            organisationId: string;
        };
        BlockHydrationResult: {
            /** Format: uuid */
            blockId: string;
            references: unknown[];
            error?: string;
        };
        AddBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            block: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
            /** Format: uuid */
            parentId?: string;
            /** Format: int32 */
            index?: number;
        };
        BlockOperation: {
            type: components["schemas"]["BlockOperationType"];
            /** Format: uuid */
            blockId: string;
        };
        /**
         * @description Enumeration of possible block operation types for requests.
         * @enum {string}
         */
        BlockOperationType: BlockOperationType;
        MoveBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            /** Format: uuid */
            fromParentId?: string;
            /** Format: uuid */
            toParentId?: string;
        };
        RemoveBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            childrenIds: {
                [key: string]: string;
            };
            /** Format: uuid */
            parentId?: string;
        };
        ReorderBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            /** Format: uuid */
            parentId: string;
            /** Format: int32 */
            fromIndex: number;
            /** Format: int32 */
            toIndex: number;
        };
        SaveEnvironmentRequest: {
            /** Format: uuid */
            layoutId: string;
            /** Format: uuid */
            organisationId: string;
            layout: components["schemas"]["TreeLayout"];
            /** Format: int32 */
            version: number;
            operations: components["schemas"]["StructuralOperationRequest"][];
        };
        StructuralOperationRequest: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            timestamp: string;
            data: components["schemas"]["AddBlockOperation"] | components["schemas"]["MoveBlockOperation"] | components["schemas"]["RemoveBlockOperation"] | components["schemas"]["ReorderBlockOperation"] | components["schemas"]["UpdateBlockOperation"] | components["schemas"]["AddBlockOperation"] | components["schemas"]["RemoveBlockOperation"] | components["schemas"]["MoveBlockOperation"] | components["schemas"]["UpdateBlockOperation"] | components["schemas"]["ReorderBlockOperation"];
        };
        UpdateBlockOperation: WithRequired<components["schemas"]["BlockOperation"], "blockId" | "type"> & {
            updatedContent: components["schemas"]["ContentNode"] | components["schemas"]["ReferenceNode"];
        };
        SaveEnvironmentResponse: {
            success: boolean;
            error?: string;
            /** Format: int32 */
            newVersion?: number;
            conflict: boolean;
            layout?: components["schemas"]["TreeLayout"];
            /** Format: int32 */
            latestVersion?: number;
            lastModifiedBy?: string;
            /** Format: date-time */
            lastModifiedAt?: string;
            idMappings: {
                [key: string]: string;
            };
        };
        /**
         * @description Enumeration of possible entity types within the system.
         * @enum {string}
         */
        ApplicationEntityType: ApplicationEntityType;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User ID in request does not match session user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                role: components["schemas"]["OrganisationRoles"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationMember"];
                };
            };
        };
    };
    updateOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Organisation"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationCreationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    updateBlockType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockType"];
            };
        };
        responses: {
            /** @description Block type updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateArchiveStatusByBlockTypeId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockTypeId: string;
                status: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block type archived successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteToOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                email: string;
                role: components["schemas"]["OrganisationRoles"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createEntityType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityTypeRequest"];
            };
        };
        responses: {
            /** @description Entity type created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
        };
    };
    publishBlockType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlockTypeRequest"];
            };
        };
        responses: {
            /** @description Block type created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
        };
    };
    overwriteBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverwriteEnvironmentRequest"];
            };
        };
        responses: {
            /** @description Environment overwritten successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OverwriteEnvironmentResponse"];
                };
            };
        };
    };
    hydrateBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HydrateBlocksRequest"];
            };
        };
        responses: {
            /** @description Blocks hydrated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["BlockHydrationResult"];
                    };
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["BlockHydrationResult"];
                    };
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["BlockHydrationResult"];
                    };
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["BlockHydrationResult"];
                    };
                };
            };
        };
    };
    saveBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveEnvironmentRequest"];
            };
        };
        responses: {
            /** @description Environment saved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
            /** @description Conflict in versioning when saving environment */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaveEnvironmentResponse"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User does not have permission to access this profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    deleteUserProfileById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have permission to delete this profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrganisation: {
        parameters: {
            query?: {
                includeMetadata?: boolean;
            };
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Organisation"];
                };
            };
        };
    };
    deleteOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"][];
                };
            };
        };
    };
    getOrganisationInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganisationInvite"][];
                };
            };
        };
    };
    getEntityTypesForOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity types retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"][];
                };
            };
            /** @description Organisation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"][];
                };
            };
        };
    };
    getEntityTypeByKeyForOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity type retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
            /** @description Entity type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntityType"];
                };
            };
        };
    };
    getBlockTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block types retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
            /** @description No block types found for the organisation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"][];
                };
            };
        };
    };
    getBlockTypeByKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block type retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
            /** @description Block type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockType"];
                };
            };
        };
    };
    getBlockEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                type: components["schemas"]["ApplicationEntityType"];
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockEnvironment"];
                };
            };
        };
    };
    removeMemberFromOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisationId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum OrganisationInviteStatus {
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    DECLINED = "DECLINED",
    EXPIRED = "EXPIRED"
}
export enum OrganisationPlan {
    FREE = "FREE",
    STARTUP = "STARTUP",
    SCALE = "SCALE",
    ENTERPRISE = "ENTERPRISE"
}
export enum OrganisationRoles {
    OWNER = "OWNER",
    ADMIN = "ADMIN",
    MEMBER = "MEMBER"
}
export enum BlockFetchPolicy {
    INHERIT = "INHERIT",
    LAZY = "LAZY",
    EAGER = "EAGER"
}
export enum BlockFormWidgetType {
    TEXT_INPUT = "TEXT_INPUT",
    NUMBER_INPUT = "NUMBER_INPUT",
    CHECKBOX = "CHECKBOX",
    RADIO_BUTTON = "RADIO_BUTTON",
    DROPDOWN = "DROPDOWN",
    DATE_PICKER = "DATE_PICKER",
    EMAIL_INPUT = "EMAIL_INPUT",
    PHONE_INPUT = "PHONE_INPUT",
    CURRENCY_INPUT = "CURRENCY_INPUT",
    TEXT_AREA = "TEXT_AREA",
    FILE_UPLOAD = "FILE_UPLOAD",
    SLIDER = "SLIDER",
    TOGGLE_SWITCH = "TOGGLE_SWITCH"
}
export enum ComponentType {
    LAYOUT_CONTAINER = "LAYOUT_CONTAINER",
    LIST = "LIST",
    CONTACT_CARD = "CONTACT_CARD",
    ADDRESS_CARD = "ADDRESS_CARD",
    LINE_ITEM = "LINE_ITEM",
    TABLE = "TABLE",
    IMAGE = "IMAGE",
    BUTTON = "BUTTON",
    ATTACHMENT = "ATTACHMENT",
    TEXT = "TEXT",
    FALLBACK = "FALLBACK"
}
export enum DataFormat {
    DATE = "DATE",
    DATETIME = "DATETIME",
    EMAIL = "EMAIL",
    PHONE = "PHONE",
    CURRENCY = "CURRENCY",
    URL = "URL",
    PERCENTAGE = "PERCENTAGE"
}
export enum DataType {
    STRING = "STRING",
    NUMBER = "NUMBER",
    BOOLEAN = "BOOLEAN",
    OBJECT = "OBJECT",
    ARRAY = "ARRAY",
    NULL = "NULL"
}
export enum Op {
    EXISTS = "EXISTS",
    EQUALS = "EQUALS",
    NOT_EQUALS = "NOT_EQUALS",
    GT = "GT",
    GTE = "GTE",
    LT = "LT",
    LTE = "LTE",
    IN = "IN",
    NOT_IN = "NOT_IN",
    EMPTY = "EMPTY",
    NOT_EMPTY = "NOT_EMPTY"
}
export enum OptionSortingType {
    MANUAL = "MANUAL",
    ALPHABETICAL = "ALPHABETICAL",
    REVERSE_ALPHABETICAL = "REVERSE_ALPHABETICAL"
}
export enum ValidationScope {
    SOFT = "SOFT",
    STRICT = "STRICT",
    NONE = "NONE"
}
export enum EntityCategory {
    STANDARD = "STANDARD",
    RELATIONSHIP = "RELATIONSHIP"
}
export enum EntityRelationshipCardinality {
    ONE_TO_ONE = "ONE_TO_ONE",
    ONE_TO_MANY = "ONE_TO_MANY",
    MANY_TO_ONE = "MANY_TO_ONE",
    MANY_TO_MANY = "MANY_TO_MANY"
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
export enum BlockListOrderingMode {
    MANUAL = "MANUAL",
    SORTED = "SORTED"
}
export enum BlockMetadataType {
    CONTENT = "CONTENT",
    ENTITY_REFERENCE = "ENTITY_REFERENCE",
    BLOCK_REFERENCE = "BLOCK_REFERENCE"
}
export enum BlockReferenceFetchPolicy {
    LAZY = "LAZY",
    EAGER = "EAGER"
}
export enum BlockReferenceWarning {
    MISSING = "MISSING",
    REQUIRES_LOADING = "REQUIRES_LOADING",
    UNSUPPORTED = "UNSUPPORTED",
    CIRCULAR = "CIRCULAR",
    DEPTH_EXCEEDED = "DEPTH_EXCEEDED"
}
export enum ListFilterLogicType {
    AND = "AND",
    OR = "OR"
}
export enum NodeType {
    REFERENCE = "REFERENCE",
    CONTENT = "CONTENT",
    ERROR = "ERROR"
}
export enum Presentation {
    SUMMARY = "SUMMARY",
    ENTITY = "ENTITY",
    TABLE = "TABLE",
    GRID = "GRID",
    INLINE = "INLINE"
}
export enum ReferenceType {
    BLOCK = "BLOCK",
    ENTITY = "ENTITY"
}
export enum RenderType {
    LIST = "LIST",
    COMPONENT = "COMPONENT",
    CONTAINER = "CONTAINER"
}
export enum SortDir {
    ASC = "ASC",
    DESC = "DESC"
}
export enum BlockOperationType {
    ADD_BLOCK = "ADD_BLOCK",
    REMOVE_BLOCK = "REMOVE_BLOCK",
    MOVE_BLOCK = "MOVE_BLOCK",
    UPDATE_BLOCK = "UPDATE_BLOCK",
    REORDER_BLOCK = "REORDER_BLOCK"
}
export enum ApplicationEntityType {
    ORGANISATION = "ORGANISATION",
    BLOCK_TYPE = "BLOCK_TYPE",
    BLOCK = "BLOCK",
    USER = "USER",
    ENTITY = "ENTITY",
    ENTITY_TYPE = "ENTITY_TYPE"
}
